<?php

namespace Database\Seeders;

use App\Models\BuildingType;
use App\Models\DisasterType;
use Illuminate\Database\Seeder;

class BuildingAndDisasterSeeder extends Seeder
{
    public function run(): void
    {
        // Building Types
        $buildingTypes = [
            [
                'name' => 'Cottage',
                'slug' => 'cottage',
                'description' => 'A simple dwelling for peasants and commoners.',
                'category' => 'housing',
                'construction_requirements' => ['wood' => 20, 'stone' => 5],
                'construction_days' => 7,
                'construction_labor' => 10,
                'maintenance_cost' => 5,
                'capacity' => 4,
                'bonuses' => [],
                'is_fortification' => false,
            ],
            [
                'name' => 'Manor House',
                'slug' => 'manor-house',
                'description' => 'A grand residence for nobility.',
                'category' => 'housing',
                'construction_requirements' => ['wood' => 50, 'stone' => 100, 'iron' => 10],
                'construction_days' => 30,
                'construction_labor' => 50,
                'maintenance_cost' => 50,
                'capacity' => 20,
                'bonuses' => ['prestige' => 10],
                'is_fortification' => false,
            ],
            [
                'name' => 'Smithy',
                'slug' => 'smithy',
                'description' => 'A blacksmith workshop for forging metal goods.',
                'category' => 'economic',
                'construction_requirements' => ['wood' => 30, 'stone' => 40, 'iron' => 20],
                'construction_days' => 14,
                'construction_labor' => 20,
                'maintenance_cost' => 20,
                'capacity' => 0,
                'bonuses' => ['smithing_bonus' => 10],
                'is_fortification' => false,
            ],
            [
                'name' => 'Market',
                'slug' => 'market',
                'description' => 'A marketplace for buying and selling goods.',
                'category' => 'economic',
                'construction_requirements' => ['wood' => 40, 'stone' => 20],
                'construction_days' => 10,
                'construction_labor' => 15,
                'maintenance_cost' => 15,
                'capacity' => 50,
                'bonuses' => ['trade_bonus' => 15],
                'is_fortification' => false,
            ],
            [
                'name' => 'Granary',
                'slug' => 'granary',
                'description' => 'Storage for grain and foodstuffs.',
                'category' => 'economic',
                'construction_requirements' => ['wood' => 50, 'stone' => 20],
                'construction_days' => 7,
                'construction_labor' => 10,
                'maintenance_cost' => 10,
                'capacity' => 500,
                'bonuses' => ['food_storage' => 500],
                'is_fortification' => false,
            ],
            [
                'name' => 'Palisade Wall',
                'slug' => 'palisade-wall',
                'description' => 'Wooden defensive wall.',
                'category' => 'military',
                'construction_requirements' => ['wood' => 100],
                'construction_days' => 14,
                'construction_labor' => 30,
                'maintenance_cost' => 10,
                'capacity' => 0,
                'bonuses' => ['defense' => 10],
                'is_fortification' => true,
            ],
            [
                'name' => 'Stone Wall',
                'slug' => 'stone-wall',
                'description' => 'Strong stone defensive wall.',
                'category' => 'military',
                'construction_requirements' => ['stone' => 200, 'iron' => 20],
                'construction_days' => 30,
                'construction_labor' => 60,
                'maintenance_cost' => 20,
                'capacity' => 0,
                'bonuses' => ['defense' => 30],
                'is_fortification' => true,
            ],
            [
                'name' => 'Chapel',
                'slug' => 'chapel',
                'description' => 'A small place of worship.',
                'category' => 'religious',
                'construction_requirements' => ['wood' => 30, 'stone' => 40],
                'construction_days' => 14,
                'construction_labor' => 20,
                'maintenance_cost' => 10,
                'capacity' => 30,
                'bonuses' => ['faith_bonus' => 5],
                'is_fortification' => false,
            ],
            [
                'name' => 'Well',
                'slug' => 'well',
                'description' => 'A source of fresh water.',
                'category' => 'infrastructure',
                'construction_requirements' => ['stone' => 30],
                'construction_days' => 5,
                'construction_labor' => 10,
                'maintenance_cost' => 2,
                'capacity' => 0,
                'bonuses' => ['health_bonus' => 5],
                'is_fortification' => false,
            ],
            [
                'name' => 'Road',
                'slug' => 'road',
                'description' => 'Paved road for faster travel.',
                'category' => 'infrastructure',
                'construction_requirements' => ['stone' => 50],
                'construction_days' => 7,
                'construction_labor' => 15,
                'maintenance_cost' => 5,
                'capacity' => 0,
                'bonuses' => ['travel_speed' => 10],
                'is_fortification' => false,
            ],
        ];

        foreach ($buildingTypes as $type) {
            BuildingType::updateOrCreate(['slug' => $type['slug']], $type);
        }

        // Disaster Types
        $disasterTypes = [
            [
                'name' => 'Drought',
                'slug' => 'drought',
                'description' => 'A prolonged period without rain, damaging crops.',
                'category' => 'weather',
                'affected_seasons' => ['summer'],
                'base_chance' => 3,
                'duration_days' => 14,
                'building_damage' => 0,
                'crop_damage' => 50,
                'casualty_rate' => 0,
                'preventable_by' => ['well'],
            ],
            [
                'name' => 'Flood',
                'slug' => 'flood',
                'description' => 'Rivers overflow, damaging buildings and crops.',
                'category' => 'weather',
                'affected_seasons' => ['spring', 'autumn'],
                'base_chance' => 2,
                'duration_days' => 3,
                'building_damage' => 30,
                'crop_damage' => 40,
                'casualty_rate' => 5,
                'preventable_by' => ['stone-wall'],
            ],
            [
                'name' => 'Fire',
                'slug' => 'fire',
                'description' => 'An uncontrolled fire spreads through the settlement.',
                'category' => 'fire',
                'affected_seasons' => ['summer', 'autumn'],
                'base_chance' => 2,
                'duration_days' => 1,
                'building_damage' => 50,
                'crop_damage' => 20,
                'casualty_rate' => 10,
                'preventable_by' => ['well', 'stone-wall'],
            ],
            [
                'name' => 'Storm',
                'slug' => 'storm',
                'description' => 'A violent storm with strong winds and lightning.',
                'category' => 'weather',
                'affected_seasons' => ['spring', 'summer', 'autumn'],
                'base_chance' => 5,
                'duration_days' => 1,
                'building_damage' => 20,
                'crop_damage' => 15,
                'casualty_rate' => 2,
                'preventable_by' => [],
            ],
            [
                'name' => 'Earthquake',
                'slug' => 'earthquake',
                'description' => 'The ground shakes violently, collapsing buildings.',
                'category' => 'geological',
                'affected_seasons' => null,
                'base_chance' => 1,
                'duration_days' => 1,
                'building_damage' => 60,
                'crop_damage' => 10,
                'casualty_rate' => 15,
                'preventable_by' => [],
            ],
            [
                'name' => 'Blizzard',
                'slug' => 'blizzard',
                'description' => 'A severe snowstorm that halts all activity.',
                'category' => 'weather',
                'affected_seasons' => ['winter'],
                'base_chance' => 5,
                'duration_days' => 3,
                'building_damage' => 10,
                'crop_damage' => 0,
                'casualty_rate' => 5,
                'preventable_by' => [],
            ],
        ];

        foreach ($disasterTypes as $type) {
            DisasterType::updateOrCreate(['slug' => $type['slug']], $type);
        }
    }
}
