<?php

namespace Database\Seeders;

use App\Models\CropType;
use App\Models\Item;
use Illuminate\Database\Seeder;

class CropTypeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Map crop slugs to their harvest item names
        $harvestItemMap = [
            'wheat' => 'Wheat',
            'potatoes' => 'Potatoes',
            'carrots' => 'Carrots',
            'cabbage' => 'Cabbage',
            'onions' => 'Onions',
            'corn' => 'Corn',
            'tomatoes' => 'Tomatoes',
            'pumpkins' => 'Pumpkins',
            'grapes' => 'Grapes',
            'hops' => 'Hops',
            'herbs' => 'Farm Herbs',
            'flax' => 'Flax',
            // Personal food crops
            'strawberries' => 'Strawberries',
            'blueberries' => 'Blueberries',
            'raspberries' => 'Raspberries',
            'watermelon' => 'Watermelon',
            'melon' => 'Melon',
            'peppers' => 'Peppers',
            'lettuce' => 'Lettuce',
            'squash' => 'Squash',
            'beans' => 'Beans',
            'cucumber' => 'Cucumber',
            // More fruits
            'apple' => 'Apple',
            'orange' => 'Orange',
            'lemon' => 'Lemon',
            'cherries' => 'Cherries',
            'peach' => 'Peach',
            'pear' => 'Pear',
            'plum' => 'Plum',
            'fig' => 'Fig',
            'pomegranate' => 'Pomegranate',
            // More vegetables
            'turnip' => 'Turnip',
            'beet' => 'Beet',
            'radish' => 'Radish',
            'spinach' => 'Spinach',
            'kale' => 'Kale',
            'broccoli' => 'Broccoli',
            'cauliflower' => 'Cauliflower',
            'garlic' => 'Garlic',
            'leek' => 'Leek',
            'parsnip' => 'Parsnip',
            'sweet_potato' => 'Sweet Potato',
            'artichoke' => 'Artichoke',
            'eggplant' => 'Eggplant',
            'zucchini' => 'Zucchini',
            // Grains
            'barley' => 'Barley',
            'oats' => 'Oats',
            'rye' => 'Rye',
            'rice' => 'Rice',
            'sunflower' => 'Sunflower Seeds',
            // Exotic high-level crops (65+)
            'dragon_fruit' => 'Dragon Fruit',
            'starfruit' => 'Starfruit',
            'ancient_grain' => 'Ancient Grain',
            'moonberry' => 'Moonberry',
            'blood_orange' => 'Blood Orange',
            'saffron' => 'Saffron',
            'vanilla' => 'Vanilla Pod',
            'cocoa' => 'Cocoa Beans',
            'coffee' => 'Coffee Beans',
            'tea' => 'Tea Leaves',
            'sugar_cane' => 'Sugar Cane',
            'giant_pumpkin' => 'Giant Pumpkin',
            'prized_melon' => 'Prized Melon',
            'golden_wheat' => 'Golden Wheat',
            'elderberry' => 'Elderberry',
            'mandrake' => 'Mandrake Root',
            'crystal_grape' => 'Crystal Grape',
            'void_pepper' => 'Void Pepper',
            'celestial_carrot' => 'Celestial Carrot',
        ];

        $crops = [
            // Basic crops (low level, fast growth)
            [
                'name' => 'Wheat',
                'slug' => 'wheat',
                'icon' => 'wheat',
                'description' => 'The staple grain of the realm. Quick to grow and essential for bread.',
                'grow_time_minutes' => 30,
                'farming_level_required' => 1,
                'farming_xp' => 400,
                'yield_min' => 2,
                'yield_max' => 5,
                'plant_cost' => 5,
                'seasons' => ['spring', 'summer', 'autumn'],
            ],
            [
                'name' => 'Potatoes',
                'slug' => 'potatoes',
                'icon' => 'potato',
                'description' => 'Hardy root vegetables that grow well in most conditions.',
                'grow_time_minutes' => 45,
                'farming_level_required' => 1,
                'farming_xp' => 500,
                'yield_min' => 3,
                'yield_max' => 6,
                'plant_cost' => 8,
                'seasons' => ['spring', 'summer'],
            ],
            [
                'name' => 'Carrots',
                'slug' => 'carrots',
                'icon' => 'carrot',
                'description' => 'Orange root vegetables, good for stews and horse feed.',
                'grow_time_minutes' => 40,
                'farming_level_required' => 5,
                'farming_xp' => 600,
                'yield_min' => 2,
                'yield_max' => 5,
                'plant_cost' => 10,
                'seasons' => ['spring', 'autumn'],
            ],
            [
                'name' => 'Cabbage',
                'slug' => 'cabbage',
                'icon' => 'salad',
                'description' => 'Leafy green vegetables perfect for soups and salads.',
                'grow_time_minutes' => 50,
                'farming_level_required' => 10,
                'farming_xp' => 750,
                'yield_min' => 1,
                'yield_max' => 3,
                'plant_cost' => 12,
                'seasons' => ['spring', 'autumn'],
            ],
            [
                'name' => 'Onions',
                'slug' => 'onions',
                'icon' => 'circle',
                'description' => 'Pungent bulbs used in countless recipes.',
                'grow_time_minutes' => 60,
                'farming_level_required' => 15,
                'farming_xp' => 900,
                'yield_min' => 2,
                'yield_max' => 4,
                'plant_cost' => 15,
                'seasons' => ['spring', 'summer'],
            ],
            // Intermediate crops
            [
                'name' => 'Corn',
                'slug' => 'corn',
                'icon' => 'wheat',
                'description' => 'Tall stalks bearing golden ears. Great for feed and flour.',
                'grow_time_minutes' => 90,
                'farming_level_required' => 20,
                'farming_xp' => 1250,
                'yield_min' => 3,
                'yield_max' => 7,
                'plant_cost' => 20,
                'seasons' => ['summer'],
            ],
            [
                'name' => 'Tomatoes',
                'slug' => 'tomatoes',
                'icon' => 'apple',
                'description' => 'Red fruits that brighten any dish.',
                'grow_time_minutes' => 75,
                'farming_level_required' => 25,
                'farming_xp' => 1100,
                'yield_min' => 2,
                'yield_max' => 6,
                'plant_cost' => 18,
                'seasons' => ['summer'],
            ],
            [
                'name' => 'Pumpkins',
                'slug' => 'pumpkins',
                'icon' => 'citrus',
                'description' => 'Large orange gourds, festive and nutritious.',
                'grow_time_minutes' => 120,
                'farming_level_required' => 30,
                'farming_xp' => 1750,
                'yield_min' => 1,
                'yield_max' => 3,
                'plant_cost' => 25,
                'seasons' => ['autumn'],
            ],
            // Advanced crops
            [
                'name' => 'Grapes',
                'slug' => 'grapes',
                'icon' => 'grape',
                'description' => 'Sweet clusters perfect for wine making.',
                'grow_time_minutes' => 180,
                'farming_level_required' => 40,
                'farming_xp' => 2500,
                'yield_min' => 3,
                'yield_max' => 8,
                'plant_cost' => 40,
                'seasons' => ['summer', 'autumn'],
            ],
            [
                'name' => 'Hops',
                'slug' => 'hops',
                'icon' => 'hop',
                'description' => 'Essential ingredient for brewing fine ales.',
                'grow_time_minutes' => 150,
                'farming_level_required' => 35,
                'farming_xp' => 2250,
                'yield_min' => 2,
                'yield_max' => 5,
                'plant_cost' => 35,
                'seasons' => ['summer'],
            ],
            // Herbs
            [
                'name' => 'Herbs',
                'slug' => 'herbs',
                'icon' => 'leaf',
                'description' => 'Aromatic plants used in cooking and medicine.',
                'grow_time_minutes' => 25,
                'farming_level_required' => 10,
                'farming_xp' => 600,
                'yield_min' => 1,
                'yield_max' => 4,
                'plant_cost' => 15,
                'seasons' => null, // All seasons
            ],
            [
                'name' => 'Flax',
                'slug' => 'flax',
                'icon' => 'flower',
                'description' => 'Blue-flowered plant used for linen and oil.',
                'grow_time_minutes' => 100,
                'farming_level_required' => 45,
                'farming_xp' => 2000,
                'yield_min' => 2,
                'yield_max' => 5,
                'plant_cost' => 30,
                'seasons' => ['spring', 'summer'],
            ],
            // Personal food crops (berries and fruits)
            [
                'name' => 'Strawberries',
                'slug' => 'strawberries',
                'icon' => 'cherry',
                'description' => 'Sweet red berries. Quick to grow and delicious to eat.',
                'grow_time_minutes' => 20,
                'farming_level_required' => 1,
                'farming_xp' => 300,
                'yield_min' => 3,
                'yield_max' => 8,
                'plant_cost' => 8,
                'seasons' => ['spring', 'summer'],
            ],
            [
                'name' => 'Blueberries',
                'slug' => 'blueberries',
                'icon' => 'cherry',
                'description' => 'Plump blue berries that grow in clusters.',
                'grow_time_minutes' => 25,
                'farming_level_required' => 5,
                'farming_xp' => 400,
                'yield_min' => 4,
                'yield_max' => 10,
                'plant_cost' => 10,
                'seasons' => ['spring', 'summer'],
            ],
            [
                'name' => 'Raspberries',
                'slug' => 'raspberries',
                'icon' => 'cherry',
                'description' => 'Delicate berries with a sweet-tart flavor.',
                'grow_time_minutes' => 25,
                'farming_level_required' => 8,
                'farming_xp' => 450,
                'yield_min' => 3,
                'yield_max' => 8,
                'plant_cost' => 12,
                'seasons' => ['summer'],
            ],
            [
                'name' => 'Lettuce',
                'slug' => 'lettuce',
                'icon' => 'salad',
                'description' => 'Fast-growing leafy greens.',
                'grow_time_minutes' => 15,
                'farming_level_required' => 1,
                'farming_xp' => 250,
                'yield_min' => 2,
                'yield_max' => 5,
                'plant_cost' => 5,
                'seasons' => ['spring', 'autumn'],
            ],
            [
                'name' => 'Cucumber',
                'slug' => 'cucumber',
                'icon' => 'banana',
                'description' => 'Cool refreshing cucumbers that grow on vines.',
                'grow_time_minutes' => 35,
                'farming_level_required' => 12,
                'farming_xp' => 550,
                'yield_min' => 2,
                'yield_max' => 5,
                'plant_cost' => 10,
                'seasons' => ['summer'],
            ],
            [
                'name' => 'Peppers',
                'slug' => 'peppers',
                'icon' => 'flame',
                'description' => 'Colorful bell peppers in various colors.',
                'grow_time_minutes' => 55,
                'farming_level_required' => 18,
                'farming_xp' => 800,
                'yield_min' => 2,
                'yield_max' => 6,
                'plant_cost' => 14,
                'seasons' => ['summer'],
            ],
            [
                'name' => 'Beans',
                'slug' => 'beans',
                'icon' => 'bean',
                'description' => 'Nutritious beans that grow on climbing vines.',
                'grow_time_minutes' => 40,
                'farming_level_required' => 15,
                'farming_xp' => 700,
                'yield_min' => 4,
                'yield_max' => 10,
                'plant_cost' => 12,
                'seasons' => ['spring', 'summer'],
            ],
            [
                'name' => 'Melon',
                'slug' => 'melon',
                'icon' => 'citrus',
                'description' => 'Sweet cantaloupe melons.',
                'grow_time_minutes' => 80,
                'farming_level_required' => 28,
                'farming_xp' => 1400,
                'yield_min' => 1,
                'yield_max' => 3,
                'plant_cost' => 22,
                'seasons' => ['summer'],
            ],
            [
                'name' => 'Watermelon',
                'slug' => 'watermelon',
                'icon' => 'citrus',
                'description' => 'Large juicy watermelons. Worth the wait!',
                'grow_time_minutes' => 120,
                'farming_level_required' => 38,
                'farming_xp' => 2100,
                'yield_min' => 1,
                'yield_max' => 2,
                'plant_cost' => 35,
                'seasons' => ['summer'],
            ],
            [
                'name' => 'Squash',
                'slug' => 'squash',
                'icon' => 'citrus',
                'description' => 'Hearty squash that stores well through winter.',
                'grow_time_minutes' => 90,
                'farming_level_required' => 32,
                'farming_xp' => 1600,
                'yield_min' => 1,
                'yield_max' => 4,
                'plant_cost' => 20,
                'seasons' => ['autumn'],
            ],
            // More fruits (orchard-style, longer grow times)
            [
                'name' => 'Apple',
                'slug' => 'apple',
                'icon' => 'apple',
                'description' => 'Crisp apples from your orchard tree.',
                'grow_time_minutes' => 200,
                'farming_level_required' => 50,
                'farming_xp' => 3000,
                'yield_min' => 4,
                'yield_max' => 10,
                'plant_cost' => 50,
                'seasons' => ['spring', 'summer', 'autumn'],
            ],
            [
                'name' => 'Orange',
                'slug' => 'orange',
                'icon' => 'citrus',
                'description' => 'Sweet citrus oranges. Require warm weather.',
                'grow_time_minutes' => 220,
                'farming_level_required' => 55,
                'farming_xp' => 3250,
                'yield_min' => 3,
                'yield_max' => 8,
                'plant_cost' => 55,
                'seasons' => ['summer'],
            ],
            [
                'name' => 'Lemon',
                'slug' => 'lemon',
                'icon' => 'citrus',
                'description' => 'Tart lemons used in cooking and beverages.',
                'grow_time_minutes' => 210,
                'farming_level_required' => 52,
                'farming_xp' => 3100,
                'yield_min' => 3,
                'yield_max' => 7,
                'plant_cost' => 52,
                'seasons' => ['summer'],
            ],
            [
                'name' => 'Cherries',
                'slug' => 'cherries',
                'icon' => 'cherry',
                'description' => 'Sweet red cherries perfect for pies.',
                'grow_time_minutes' => 180,
                'farming_level_required' => 42,
                'farming_xp' => 2600,
                'yield_min' => 5,
                'yield_max' => 12,
                'plant_cost' => 45,
                'seasons' => ['spring', 'summer'],
            ],
            [
                'name' => 'Peach',
                'slug' => 'peach',
                'icon' => 'apple',
                'description' => 'Fuzzy peaches with sweet flesh.',
                'grow_time_minutes' => 190,
                'farming_level_required' => 48,
                'farming_xp' => 2750,
                'yield_min' => 3,
                'yield_max' => 8,
                'plant_cost' => 48,
                'seasons' => ['summer'],
            ],
            [
                'name' => 'Pear',
                'slug' => 'pear',
                'icon' => 'apple',
                'description' => 'Juicy pears that ripen on the tree.',
                'grow_time_minutes' => 185,
                'farming_level_required' => 46,
                'farming_xp' => 2650,
                'yield_min' => 3,
                'yield_max' => 7,
                'plant_cost' => 46,
                'seasons' => ['summer', 'autumn'],
            ],
            [
                'name' => 'Plum',
                'slug' => 'plum',
                'icon' => 'apple',
                'description' => 'Purple plums with sweet juice.',
                'grow_time_minutes' => 170,
                'farming_level_required' => 44,
                'farming_xp' => 2500,
                'yield_min' => 4,
                'yield_max' => 9,
                'plant_cost' => 44,
                'seasons' => ['summer'],
            ],
            [
                'name' => 'Fig',
                'slug' => 'fig',
                'icon' => 'apple',
                'description' => 'Ancient fruit with unique honey-like sweetness.',
                'grow_time_minutes' => 240,
                'farming_level_required' => 60,
                'farming_xp' => 3500,
                'yield_min' => 2,
                'yield_max' => 6,
                'plant_cost' => 60,
                'seasons' => ['summer', 'autumn'],
            ],
            [
                'name' => 'Pomegranate',
                'slug' => 'pomegranate',
                'icon' => 'apple',
                'description' => 'Ruby-red seeds burst with tart flavor.',
                'grow_time_minutes' => 260,
                'farming_level_required' => 65,
                'farming_xp' => 3750,
                'yield_min' => 1,
                'yield_max' => 4,
                'plant_cost' => 65,
                'seasons' => ['autumn'],
            ],
            // More vegetables
            [
                'name' => 'Turnip',
                'slug' => 'turnip',
                'icon' => 'circle',
                'description' => 'Quick-growing root vegetable. Great for beginners.',
                'grow_time_minutes' => 20,
                'farming_level_required' => 1,
                'farming_xp' => 300,
                'yield_min' => 2,
                'yield_max' => 5,
                'plant_cost' => 6,
                'seasons' => ['spring', 'autumn'],
            ],
            [
                'name' => 'Beet',
                'slug' => 'beet',
                'icon' => 'circle',
                'description' => 'Deep red beets with earthy flavor.',
                'grow_time_minutes' => 45,
                'farming_level_required' => 8,
                'farming_xp' => 600,
                'yield_min' => 2,
                'yield_max' => 4,
                'plant_cost' => 10,
                'seasons' => ['spring', 'summer', 'autumn'],
            ],
            [
                'name' => 'Radish',
                'slug' => 'radish',
                'icon' => 'circle',
                'description' => 'Spicy root that grows in no time.',
                'grow_time_minutes' => 12,
                'farming_level_required' => 1,
                'farming_xp' => 200,
                'yield_min' => 3,
                'yield_max' => 6,
                'plant_cost' => 4,
                'seasons' => ['spring', 'autumn'],
            ],
            [
                'name' => 'Spinach',
                'slug' => 'spinach',
                'icon' => 'salad',
                'description' => 'Nutrient-rich leafy greens.',
                'grow_time_minutes' => 18,
                'farming_level_required' => 3,
                'farming_xp' => 350,
                'yield_min' => 3,
                'yield_max' => 7,
                'plant_cost' => 6,
                'seasons' => ['spring', 'autumn'],
            ],
            [
                'name' => 'Kale',
                'slug' => 'kale',
                'icon' => 'salad',
                'description' => 'Hardy greens that thrive in cold weather.',
                'grow_time_minutes' => 30,
                'farming_level_required' => 6,
                'farming_xp' => 500,
                'yield_min' => 2,
                'yield_max' => 5,
                'plant_cost' => 8,
                'seasons' => ['spring', 'autumn', 'winter'],
            ],
            [
                'name' => 'Broccoli',
                'slug' => 'broccoli',
                'icon' => 'tree-deciduous',
                'description' => 'Green flowering vegetable packed with nutrients.',
                'grow_time_minutes' => 70,
                'farming_level_required' => 22,
                'farming_xp' => 1200,
                'yield_min' => 1,
                'yield_max' => 3,
                'plant_cost' => 18,
                'seasons' => ['spring', 'autumn'],
            ],
            [
                'name' => 'Cauliflower',
                'slug' => 'cauliflower',
                'icon' => 'flower',
                'description' => 'White flowering head with delicate flavor.',
                'grow_time_minutes' => 75,
                'farming_level_required' => 24,
                'farming_xp' => 1300,
                'yield_min' => 1,
                'yield_max' => 2,
                'plant_cost' => 20,
                'seasons' => ['spring', 'autumn'],
            ],
            [
                'name' => 'Garlic',
                'slug' => 'garlic',
                'icon' => 'circle',
                'description' => 'Pungent bulbs essential for cooking.',
                'grow_time_minutes' => 100,
                'farming_level_required' => 30,
                'farming_xp' => 1500,
                'yield_min' => 3,
                'yield_max' => 8,
                'plant_cost' => 22,
                'seasons' => ['spring', 'autumn'],
            ],
            [
                'name' => 'Leek',
                'slug' => 'leek',
                'icon' => 'pilcrow',
                'description' => 'Mild onion-like vegetable great in soups.',
                'grow_time_minutes' => 85,
                'farming_level_required' => 26,
                'farming_xp' => 1400,
                'yield_min' => 2,
                'yield_max' => 4,
                'plant_cost' => 18,
                'seasons' => ['spring', 'autumn', 'winter'],
            ],
            [
                'name' => 'Parsnip',
                'slug' => 'parsnip',
                'icon' => 'carrot',
                'description' => 'Sweet white root that improves after frost.',
                'grow_time_minutes' => 110,
                'farming_level_required' => 35,
                'farming_xp' => 1900,
                'yield_min' => 2,
                'yield_max' => 4,
                'plant_cost' => 25,
                'seasons' => ['autumn', 'winter'],
            ],
            [
                'name' => 'Sweet Potato',
                'slug' => 'sweet_potato',
                'icon' => 'potato',
                'description' => 'Sweet orange tubers that store well.',
                'grow_time_minutes' => 95,
                'farming_level_required' => 28,
                'farming_xp' => 1500,
                'yield_min' => 2,
                'yield_max' => 5,
                'plant_cost' => 20,
                'seasons' => ['summer', 'autumn'],
            ],
            [
                'name' => 'Artichoke',
                'slug' => 'artichoke',
                'icon' => 'flower',
                'description' => 'Exotic thistle with edible heart.',
                'grow_time_minutes' => 150,
                'farming_level_required' => 45,
                'farming_xp' => 2400,
                'yield_min' => 1,
                'yield_max' => 3,
                'plant_cost' => 40,
                'seasons' => ['spring', 'summer'],
            ],
            [
                'name' => 'Eggplant',
                'slug' => 'eggplant',
                'icon' => 'egg',
                'description' => 'Purple fruits used in many cuisines.',
                'grow_time_minutes' => 65,
                'farming_level_required' => 20,
                'farming_xp' => 1000,
                'yield_min' => 2,
                'yield_max' => 5,
                'plant_cost' => 16,
                'seasons' => ['summer'],
            ],
            [
                'name' => 'Zucchini',
                'slug' => 'zucchini',
                'icon' => 'banana',
                'description' => 'Prolific summer squash. Grows fast!',
                'grow_time_minutes' => 40,
                'farming_level_required' => 14,
                'farming_xp' => 700,
                'yield_min' => 3,
                'yield_max' => 7,
                'plant_cost' => 12,
                'seasons' => ['summer'],
            ],
            // Grains
            [
                'name' => 'Barley',
                'slug' => 'barley',
                'icon' => 'wheat',
                'description' => 'Hardy grain used for bread and beer.',
                'grow_time_minutes' => 55,
                'farming_level_required' => 12,
                'farming_xp' => 750,
                'yield_min' => 3,
                'yield_max' => 7,
                'plant_cost' => 12,
                'seasons' => ['spring', 'summer'],
            ],
            [
                'name' => 'Oats',
                'slug' => 'oats',
                'icon' => 'wheat',
                'description' => 'Nutritious grain for porridge and feed.',
                'grow_time_minutes' => 50,
                'farming_level_required' => 10,
                'farming_xp' => 700,
                'yield_min' => 3,
                'yield_max' => 6,
                'plant_cost' => 10,
                'seasons' => ['spring', 'summer'],
            ],
            [
                'name' => 'Rye',
                'slug' => 'rye',
                'icon' => 'wheat',
                'description' => 'Hearty grain that grows in poor soil.',
                'grow_time_minutes' => 60,
                'farming_level_required' => 15,
                'farming_xp' => 900,
                'yield_min' => 2,
                'yield_max' => 5,
                'plant_cost' => 14,
                'seasons' => ['spring', 'autumn'],
            ],
            [
                'name' => 'Rice',
                'slug' => 'rice',
                'icon' => 'wheat',
                'description' => 'Staple grain requiring wet conditions.',
                'grow_time_minutes' => 80,
                'farming_level_required' => 25,
                'farming_xp' => 1250,
                'yield_min' => 4,
                'yield_max' => 10,
                'plant_cost' => 18,
                'seasons' => ['summer'],
            ],
            [
                'name' => 'Sunflower',
                'slug' => 'sunflower',
                'icon' => 'sun',
                'description' => 'Tall flowers that produce nutritious seeds.',
                'grow_time_minutes' => 130,
                'farming_level_required' => 40,
                'farming_xp' => 2250,
                'yield_min' => 5,
                'yield_max' => 15,
                'plant_cost' => 30,
                'seasons' => ['summer'],
            ],
            // Exotic high-level crops (65+)
            [
                'name' => 'Tea',
                'slug' => 'tea',
                'icon' => 'leaf',
                'description' => 'Fragrant tea bushes. Leaves calm the spirit.',
                'grow_time_minutes' => 140,
                'farming_level_required' => 58,
                'farming_xp' => 2750,
                'yield_min' => 4,
                'yield_max' => 10,
                'plant_cost' => 45,
                'seasons' => ['spring', 'summer'],
            ],
            [
                'name' => 'Sugar Cane',
                'slug' => 'sugar_cane',
                'icon' => 'pilcrow',
                'description' => 'Tall sweet stalks that thrive in wet conditions.',
                'grow_time_minutes' => 120,
                'farming_level_required' => 55,
                'farming_xp' => 2400,
                'yield_min' => 5,
                'yield_max' => 12,
                'plant_cost' => 40,
                'seasons' => ['summer'],
            ],
            [
                'name' => 'Coffee',
                'slug' => 'coffee',
                'icon' => 'bean',
                'description' => 'Coffee plants bearing energizing beans.',
                'grow_time_minutes' => 180,
                'farming_level_required' => 62,
                'farming_xp' => 3250,
                'yield_min' => 3,
                'yield_max' => 8,
                'plant_cost' => 55,
                'seasons' => ['summer'],
            ],
            [
                'name' => 'Dragon Fruit',
                'slug' => 'dragon_fruit',
                'icon' => 'flame',
                'description' => 'Exotic cactus fruit with striking pink skin.',
                'grow_time_minutes' => 200,
                'farming_level_required' => 65,
                'farming_xp' => 3750,
                'yield_min' => 2,
                'yield_max' => 5,
                'plant_cost' => 70,
                'seasons' => ['summer'],
            ],
            [
                'name' => 'Blood Orange',
                'slug' => 'blood_orange',
                'icon' => 'citrus',
                'description' => 'Rare citrus with crimson flesh.',
                'grow_time_minutes' => 190,
                'farming_level_required' => 66,
                'farming_xp' => 3600,
                'yield_min' => 2,
                'yield_max' => 6,
                'plant_cost' => 65,
                'seasons' => ['summer', 'autumn'],
            ],
            [
                'name' => 'Cocoa',
                'slug' => 'cocoa',
                'icon' => 'bean',
                'description' => 'Tropical cocoa trees. For chocolate lovers.',
                'grow_time_minutes' => 220,
                'farming_level_required' => 68,
                'farming_xp' => 4000,
                'yield_min' => 3,
                'yield_max' => 7,
                'plant_cost' => 75,
                'seasons' => ['summer'],
            ],
            [
                'name' => 'Moonberry',
                'slug' => 'moonberry',
                'icon' => 'moon',
                'description' => 'Mystical berries that bloom only under moonlight.',
                'grow_time_minutes' => 240,
                'farming_level_required' => 70,
                'farming_xp' => 4250,
                'yield_min' => 2,
                'yield_max' => 6,
                'plant_cost' => 80,
                'seasons' => ['autumn', 'winter'],
            ],
            [
                'name' => 'Starfruit',
                'slug' => 'starfruit',
                'icon' => 'star',
                'description' => 'Golden fruit shaped like a star. Said to fall from the heavens.',
                'grow_time_minutes' => 280,
                'farming_level_required' => 72,
                'farming_xp' => 4750,
                'yield_min' => 1,
                'yield_max' => 4,
                'plant_cost' => 100,
                'seasons' => ['summer'],
            ],
            [
                'name' => 'Elderberry',
                'slug' => 'elderberry',
                'icon' => 'cherry',
                'description' => 'Dark berries with potent medicinal properties.',
                'grow_time_minutes' => 200,
                'farming_level_required' => 68,
                'farming_xp' => 3900,
                'yield_min' => 4,
                'yield_max' => 10,
                'plant_cost' => 70,
                'seasons' => ['summer', 'autumn'],
            ],
            [
                'name' => 'Vanilla',
                'slug' => 'vanilla',
                'icon' => 'flower',
                'description' => 'Exotic orchid producing aromatic vanilla pods.',
                'grow_time_minutes' => 300,
                'farming_level_required' => 74,
                'farming_xp' => 5000,
                'yield_min' => 1,
                'yield_max' => 3,
                'plant_cost' => 120,
                'seasons' => ['summer'],
            ],
            [
                'name' => 'Giant Pumpkin',
                'slug' => 'giant_pumpkin',
                'icon' => 'citrus',
                'description' => 'Colossal pumpkins that could win any harvest festival.',
                'grow_time_minutes' => 360,
                'farming_level_required' => 75,
                'farming_xp' => 6000,
                'yield_min' => 1,
                'yield_max' => 1,
                'plant_cost' => 150,
                'seasons' => ['autumn'],
            ],
            [
                'name' => 'Ancient Grain',
                'slug' => 'ancient_grain',
                'icon' => 'wheat',
                'description' => 'Seeds from a forgotten era, infused with primordial magic.',
                'grow_time_minutes' => 320,
                'farming_level_required' => 78,
                'farming_xp' => 5500,
                'yield_min' => 2,
                'yield_max' => 5,
                'plant_cost' => 130,
                'seasons' => ['spring', 'summer'],
            ],
            [
                'name' => 'Prized Melon',
                'slug' => 'prized_melon',
                'icon' => 'citrus',
                'description' => 'A perfectly cultivated melon of legendary sweetness.',
                'grow_time_minutes' => 340,
                'farming_level_required' => 80,
                'farming_xp' => 6250,
                'yield_min' => 1,
                'yield_max' => 1,
                'plant_cost' => 160,
                'seasons' => ['summer'],
            ],
            [
                'name' => 'Saffron',
                'slug' => 'saffron',
                'icon' => 'flower',
                'description' => 'The most precious spice. Each flower yields mere threads.',
                'grow_time_minutes' => 400,
                'farming_level_required' => 82,
                'farming_xp' => 7000,
                'yield_min' => 1,
                'yield_max' => 3,
                'plant_cost' => 180,
                'seasons' => ['autumn'],
            ],
            [
                'name' => 'Mandrake',
                'slug' => 'mandrake',
                'icon' => 'skull',
                'description' => 'Magical roots that scream when harvested. Handle with care.',
                'grow_time_minutes' => 380,
                'farming_level_required' => 85,
                'farming_xp' => 7500,
                'yield_min' => 1,
                'yield_max' => 2,
                'plant_cost' => 200,
                'seasons' => ['autumn', 'winter'],
            ],
            [
                'name' => 'Golden Wheat',
                'slug' => 'golden_wheat',
                'icon' => 'wheat',
                'description' => 'Wheat touched by ancient magic. Glimmers like gold.',
                'grow_time_minutes' => 420,
                'farming_level_required' => 88,
                'farming_xp' => 8000,
                'yield_min' => 3,
                'yield_max' => 7,
                'plant_cost' => 220,
                'seasons' => ['summer'],
            ],
            [
                'name' => 'Crystal Grape',
                'slug' => 'crystal_grape',
                'icon' => 'grape',
                'description' => 'Translucent grapes that shimmer with inner light.',
                'grow_time_minutes' => 480,
                'farming_level_required' => 90,
                'farming_xp' => 9000,
                'yield_min' => 2,
                'yield_max' => 5,
                'plant_cost' => 250,
                'seasons' => ['summer', 'autumn'],
            ],
            [
                'name' => 'Void Pepper',
                'slug' => 'void_pepper',
                'icon' => 'flame',
                'description' => 'An impossibly hot pepper from another dimension.',
                'grow_time_minutes' => 500,
                'farming_level_required' => 92,
                'farming_xp' => 10000,
                'yield_min' => 1,
                'yield_max' => 3,
                'plant_cost' => 280,
                'seasons' => ['summer'],
            ],
            [
                'name' => 'Celestial Carrot',
                'slug' => 'celestial_carrot',
                'icon' => 'carrot',
                'description' => 'A perfect carrot blessed by the gods themselves.',
                'grow_time_minutes' => 600,
                'farming_level_required' => 99,
                'farming_xp' => 12500,
                'yield_min' => 1,
                'yield_max' => 2,
                'plant_cost' => 350,
                'seasons' => ['spring', 'summer', 'autumn'],
            ],
        ];

        // Map crop slugs to their seed item names
        $seedItemMap = [
            'wheat' => 'Wheat Seeds',
            'potatoes' => 'Potato Seeds',
            'carrots' => 'Carrot Seeds',
            'cabbage' => 'Cabbage Seeds',
            'onions' => 'Onion Seeds',
            'corn' => 'Corn Seeds',
            'tomatoes' => 'Tomato Seeds',
            'pumpkins' => 'Pumpkin Seeds',
            'grapes' => 'Grape Seeds',
            'hops' => 'Hop Seeds',
            'herbs' => 'Herb Seeds',
            'flax' => 'Flax Seeds',
            'strawberries' => 'Strawberry Seeds',
            'blueberries' => 'Blueberry Seeds',
            'raspberries' => 'Raspberry Seeds',
            'lettuce' => 'Lettuce Seeds',
            'cucumber' => 'Cucumber Seeds',
            'peppers' => 'Pepper Seeds',
            'beans' => 'Bean Seeds',
            'melon' => 'Melon Seeds',
            'watermelon' => 'Watermelon Seeds',
            'squash' => 'Squash Seeds',
        ];

        foreach ($crops as $crop) {
            // Look up the harvest item by name
            $harvestItemName = $harvestItemMap[$crop['slug']] ?? null;
            $harvestItem = $harvestItemName ? Item::where('name', $harvestItemName)->first() : null;

            // Look up the seed item by name
            $seedItemName = $seedItemMap[$crop['slug']] ?? null;
            $seedItem = $seedItemName ? Item::where('name', $seedItemName)->first() : null;

            $cropData = $crop;
            if ($harvestItem) {
                $cropData['harvest_item_id'] = $harvestItem->id;
            }
            if ($seedItem) {
                $cropData['seed_item_id'] = $seedItem->id;
            }

            CropType::updateOrCreate(
                ['slug' => $crop['slug']],
                $cropData
            );
        }
    }
}
