<?php

namespace Database\Seeders;

use App\Models\DiseaseType;
use Illuminate\Database\Seeder;

class DiseaseTypeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $diseaseTypes = [
            // Common ailments (high chance, low severity)
            [
                'name' => 'Common Cold',
                'slug' => 'common_cold',
                'description' => 'A mild illness causing sneezing, coughing, and fatigue.',
                'severity' => DiseaseType::SEVERITY_MINOR,
                'base_spread_rate' => 15,
                'mortality_rate' => 0,
                'base_duration_days' => 5,
                'incubation_days' => 1,
                'symptoms' => ['sneezing', 'coughing', 'fatigue', 'runny_nose'],
                'stat_penalties' => ['energy' => -10],
                'is_contagious' => true,
                'grants_immunity' => false,
            ],
            [
                'name' => 'Flux',
                'slug' => 'flux',
                'description' => 'A digestive ailment causing severe stomach cramps and weakness.',
                'severity' => DiseaseType::SEVERITY_MINOR,
                'base_spread_rate' => 5,
                'mortality_rate' => 2,
                'base_duration_days' => 4,
                'incubation_days' => 1,
                'symptoms' => ['stomach_cramps', 'vomiting', 'weakness', 'dehydration'],
                'stat_penalties' => ['energy' => -20, 'strength' => -5],
                'is_contagious' => false,
                'grants_immunity' => false,
            ],
            [
                'name' => 'Ague',
                'slug' => 'ague',
                'description' => 'A fever with chills and sweating, common in marshy areas.',
                'severity' => DiseaseType::SEVERITY_MODERATE,
                'base_spread_rate' => 0,
                'mortality_rate' => 5,
                'base_duration_days' => 10,
                'incubation_days' => 7,
                'symptoms' => ['fever', 'chills', 'sweating', 'weakness', 'headache'],
                'stat_penalties' => ['energy' => -30, 'strength' => -10],
                'is_contagious' => false,
                'grants_immunity' => false,
            ],
            [
                'name' => 'Consumption',
                'slug' => 'consumption',
                'description' => 'A wasting disease of the lungs causing persistent cough and bloody sputum.',
                'severity' => DiseaseType::SEVERITY_MODERATE,
                'base_spread_rate' => 10,
                'mortality_rate' => 15,
                'base_duration_days' => 60,
                'incubation_days' => 14,
                'symptoms' => ['coughing', 'bloody_sputum', 'weight_loss', 'night_sweats', 'fatigue'],
                'stat_penalties' => ['energy' => -40, 'strength' => -20, 'max_hp' => -10],
                'is_contagious' => true,
                'grants_immunity' => false,
            ],
            [
                'name' => 'Typhoid Fever',
                'slug' => 'typhoid',
                'description' => 'A dangerous fever spread through contaminated water.',
                'severity' => DiseaseType::SEVERITY_MODERATE,
                'base_spread_rate' => 8,
                'mortality_rate' => 12,
                'base_duration_days' => 21,
                'incubation_days' => 10,
                'symptoms' => ['high_fever', 'delirium', 'rose_spots', 'abdominal_pain', 'weakness'],
                'stat_penalties' => ['energy' => -50, 'strength' => -15],
                'is_contagious' => true,
                'grants_immunity' => true,
            ],
            [
                'name' => 'Dysentery',
                'slug' => 'dysentery',
                'description' => 'A severe intestinal infection causing bloody flux. Common in camps and sieges.',
                'severity' => DiseaseType::SEVERITY_MODERATE,
                'base_spread_rate' => 12,
                'mortality_rate' => 10,
                'base_duration_days' => 14,
                'incubation_days' => 3,
                'symptoms' => ['bloody_flux', 'severe_cramps', 'fever', 'dehydration'],
                'stat_penalties' => ['energy' => -40, 'strength' => -15],
                'is_contagious' => true,
                'grants_immunity' => false,
            ],
            [
                'name' => 'Scarlet Fever',
                'slug' => 'scarlet_fever',
                'description' => 'A disease marked by sore throat and a distinctive red rash.',
                'severity' => DiseaseType::SEVERITY_MODERATE,
                'base_spread_rate' => 20,
                'mortality_rate' => 8,
                'base_duration_days' => 10,
                'incubation_days' => 2,
                'symptoms' => ['sore_throat', 'red_rash', 'fever', 'swollen_tongue'],
                'stat_penalties' => ['energy' => -25],
                'is_contagious' => true,
                'grants_immunity' => true,
            ],
            [
                'name' => 'Smallpox',
                'slug' => 'smallpox',
                'description' => 'A highly contagious disease causing fever and distinctive pustules. Survivors are often scarred.',
                'severity' => DiseaseType::SEVERITY_SEVERE,
                'base_spread_rate' => 30,
                'mortality_rate' => 25,
                'base_duration_days' => 21,
                'incubation_days' => 12,
                'symptoms' => ['high_fever', 'pustules', 'scarring', 'blindness_risk'],
                'stat_penalties' => ['energy' => -60, 'strength' => -20, 'max_hp' => -15],
                'is_contagious' => true,
                'grants_immunity' => true,
            ],
            [
                'name' => 'Leprosy',
                'slug' => 'leprosy',
                'description' => 'A slow-progressing disease causing skin lesions and nerve damage. Sufferers are often outcast.',
                'severity' => DiseaseType::SEVERITY_SEVERE,
                'base_spread_rate' => 2,
                'mortality_rate' => 5,
                'base_duration_days' => 365,
                'incubation_days' => 180,
                'symptoms' => ['skin_lesions', 'numbness', 'deformity', 'social_stigma'],
                'stat_penalties' => ['strength' => -30, 'max_hp' => -20],
                'is_contagious' => true,
                'grants_immunity' => false,
            ],
            [
                'name' => 'Cholera',
                'slug' => 'cholera',
                'description' => 'A deadly waterborne disease causing severe dehydration. Can kill within hours.',
                'severity' => DiseaseType::SEVERITY_SEVERE,
                'base_spread_rate' => 15,
                'mortality_rate' => 30,
                'base_duration_days' => 5,
                'incubation_days' => 1,
                'symptoms' => ['severe_vomiting', 'watery_flux', 'rapid_dehydration', 'muscle_cramps'],
                'stat_penalties' => ['energy' => -70, 'strength' => -30],
                'is_contagious' => true,
                'grants_immunity' => false,
            ],
            [
                'name' => 'The Black Death',
                'slug' => 'black_death',
                'description' => 'The most feared disease known to man. Causes swollen lymph nodes, fever, and often death within days.',
                'severity' => DiseaseType::SEVERITY_PLAGUE,
                'base_spread_rate' => 40,
                'mortality_rate' => 50,
                'base_duration_days' => 7,
                'incubation_days' => 3,
                'symptoms' => ['buboes', 'high_fever', 'chills', 'black_spots', 'delirium', 'bleeding'],
                'stat_penalties' => ['energy' => -80, 'strength' => -40, 'max_hp' => -30],
                'is_contagious' => true,
                'grants_immunity' => true,
            ],
            [
                'name' => 'Sweating Sickness',
                'slug' => 'sweating_sickness',
                'description' => 'A mysterious illness. Victims are healthy at breakfast and dead by supper.',
                'severity' => DiseaseType::SEVERITY_PLAGUE,
                'base_spread_rate' => 25,
                'mortality_rate' => 40,
                'base_duration_days' => 1,
                'incubation_days' => 1,
                'symptoms' => ['profuse_sweating', 'high_fever', 'heart_palpitations', 'headache', 'delirium'],
                'stat_penalties' => ['energy' => -90, 'strength' => -50],
                'is_contagious' => true,
                'grants_immunity' => true,
            ],
            [
                'name' => 'Ergotism',
                'slug' => 'ergotism',
                'description' => 'Caused by contaminated grain. Known as St. Anthony\'s Fire for the burning sensations.',
                'severity' => DiseaseType::SEVERITY_MODERATE,
                'base_spread_rate' => 0,
                'mortality_rate' => 10,
                'base_duration_days' => 21,
                'incubation_days' => 3,
                'symptoms' => ['burning_sensation', 'hallucinations', 'convulsions', 'gangrene'],
                'stat_penalties' => ['energy' => -30, 'strength' => -20],
                'is_contagious' => false,
                'grants_immunity' => false,
            ],
            [
                'name' => 'Rabies',
                'slug' => 'rabies',
                'description' => 'A fatal disease spread through animal bites. Causes madness and hydrophobia.',
                'severity' => DiseaseType::SEVERITY_SEVERE,
                'base_spread_rate' => 0,
                'mortality_rate' => 100,
                'base_duration_days' => 10,
                'incubation_days' => 30,
                'symptoms' => ['hydrophobia', 'madness', 'aggression', 'paralysis', 'foaming_mouth'],
                'stat_penalties' => ['energy' => -50, 'strength' => -30],
                'is_contagious' => false,
                'grants_immunity' => false,
            ],
        ];

        foreach ($diseaseTypes as $type) {
            DiseaseType::updateOrCreate(
                ['slug' => $type['slug']],
                $type
            );
        }
    }
}
