<?php

namespace Database\Seeders;

use App\Models\Item;
use Illuminate\Database\Seeder;

class ItemSeeder extends Seeder
{
    /**
     * Metal tiers configuration for smithed items.
     */
    private const METAL_TIERS = [
        'Bronze' => ['base_level' => 1, 'multiplier' => 1.0, 'rarity' => 'common', 'bar_value' => 15],
        'Iron' => ['base_level' => 15, 'multiplier' => 1.5, 'rarity' => 'common', 'bar_value' => 40],
        'Steel' => ['base_level' => 30, 'multiplier' => 2.0, 'rarity' => 'uncommon', 'bar_value' => 100],
        'Mithril' => ['base_level' => 45, 'multiplier' => 3.0, 'rarity' => 'uncommon', 'bar_value' => 300],
        'Celestial' => ['base_level' => 60, 'multiplier' => 4.0, 'rarity' => 'rare', 'bar_value' => 800],
        'Oria' => ['base_level' => 75, 'multiplier' => 5.0, 'rarity' => 'epic', 'bar_value' => 1500],
    ];

    /**
     * Smithable item templates.
     * Each has: bars required, level offset, type, slot, base stats.
     */
    private const SMITHABLE_ITEMS = [
        // Weapons (11 types)
        'Dagger' => ['bars' => 1, 'offset' => 0, 'type' => 'weapon', 'subtype' => 'dagger', 'slot' => 'weapon', 'atk' => 4, 'str' => 2, 'def' => 0],
        'Axe' => ['bars' => 1, 'offset' => 1, 'type' => 'weapon', 'subtype' => 'axe', 'slot' => 'weapon', 'atk' => 6, 'str' => 4, 'def' => 0],
        'Mace' => ['bars' => 1, 'offset' => 2, 'type' => 'weapon', 'subtype' => 'mace', 'slot' => 'weapon', 'atk' => 5, 'str' => 6, 'def' => 0],
        'Sword' => ['bars' => 1, 'offset' => 4, 'type' => 'weapon', 'subtype' => 'sword', 'slot' => 'weapon', 'atk' => 8, 'str' => 5, 'def' => 0],
        'Scimitar' => ['bars' => 2, 'offset' => 5, 'type' => 'weapon', 'subtype' => 'scimitar', 'slot' => 'weapon', 'atk' => 10, 'str' => 6, 'def' => 0],
        'Spear' => ['bars' => 1, 'offset' => 5, 'type' => 'weapon', 'subtype' => 'spear', 'slot' => 'weapon', 'atk' => 7, 'str' => 4, 'def' => 0],
        'Longsword' => ['bars' => 2, 'offset' => 6, 'type' => 'weapon', 'subtype' => 'longsword', 'slot' => 'weapon', 'atk' => 12, 'str' => 8, 'def' => 0],
        'Warhammer' => ['bars' => 3, 'offset' => 9, 'type' => 'weapon', 'subtype' => 'warhammer', 'slot' => 'weapon', 'atk' => 8, 'str' => 14, 'def' => 0],
        'Battleaxe' => ['bars' => 3, 'offset' => 10, 'type' => 'weapon', 'subtype' => 'battleaxe', 'slot' => 'weapon', 'atk' => 14, 'str' => 10, 'def' => 0],
        'Claws' => ['bars' => 2, 'offset' => 13, 'type' => 'weapon', 'subtype' => 'claws', 'slot' => 'weapon', 'atk' => 16, 'str' => 4, 'def' => 0],
        '2h Sword' => ['bars' => 3, 'offset' => 14, 'type' => 'weapon', 'subtype' => '2hsword', 'slot' => 'weapon', 'atk' => 18, 'str' => 12, 'def' => 0],
        // Armor (8 types)
        'Medium Helm' => ['bars' => 1, 'offset' => 3, 'type' => 'armor', 'subtype' => 'helmet', 'slot' => 'head', 'atk' => 0, 'str' => 0, 'def' => 4],
        'Full Helm' => ['bars' => 2, 'offset' => 7, 'type' => 'armor', 'subtype' => 'helmet', 'slot' => 'head', 'atk' => 0, 'str' => 0, 'def' => 8],
        'Sq Shield' => ['bars' => 2, 'offset' => 8, 'type' => 'armor', 'subtype' => 'shield', 'slot' => 'shield', 'atk' => 0, 'str' => 0, 'def' => 10],
        'Chainbody' => ['bars' => 3, 'offset' => 11, 'type' => 'armor', 'subtype' => 'chest', 'slot' => 'chest', 'atk' => 0, 'str' => 0, 'def' => 14],
        'Kiteshield' => ['bars' => 3, 'offset' => 12, 'type' => 'armor', 'subtype' => 'shield', 'slot' => 'shield', 'atk' => 0, 'str' => 0, 'def' => 16],
        'Platelegs' => ['bars' => 3, 'offset' => 16, 'type' => 'armor', 'subtype' => 'legs', 'slot' => 'legs', 'atk' => 0, 'str' => 0, 'def' => 12],
        'Plateskirt' => ['bars' => 3, 'offset' => 16, 'type' => 'armor', 'subtype' => 'legs', 'slot' => 'legs', 'atk' => 0, 'str' => 0, 'def' => 12],
        'Platebody' => ['bars' => 5, 'offset' => 18, 'type' => 'armor', 'subtype' => 'chest', 'slot' => 'chest', 'atk' => 0, 'str' => 0, 'def' => 22],
        // Ammunition (4 types) - stackable
        'Dart Tips' => ['bars' => 1, 'offset' => 4, 'type' => 'misc', 'subtype' => 'ammunition', 'slot' => null, 'atk' => 2, 'str' => 1, 'def' => 0, 'stackable' => true, 'output_qty' => 10],
        'Arrowtips' => ['bars' => 1, 'offset' => 5, 'type' => 'misc', 'subtype' => 'ammunition', 'slot' => null, 'atk' => 2, 'str' => 1, 'def' => 0, 'stackable' => true, 'output_qty' => 15],
        'Javelin Tips' => ['bars' => 1, 'offset' => 6, 'type' => 'misc', 'subtype' => 'ammunition', 'slot' => null, 'atk' => 3, 'str' => 2, 'def' => 0, 'stackable' => true, 'output_qty' => 5],
        'Throwing Knives' => ['bars' => 1, 'offset' => 7, 'type' => 'weapon', 'subtype' => 'throwing', 'slot' => 'weapon', 'atk' => 3, 'str' => 2, 'def' => 0, 'stackable' => true, 'output_qty' => 5],
    ];

    /**
     * Generate all smithed items for all metal tiers.
     *
     * @return array<int, array<string, mixed>>
     */
    private function generateSmithedItems(): array
    {
        $items = [];

        foreach (self::METAL_TIERS as $metal => $tierData) {
            foreach (self::SMITHABLE_ITEMS as $itemName => $itemData) {
                $level = $tierData['base_level'] + $itemData['offset'];
                $multiplier = $tierData['multiplier'];
                $isStackable = $itemData['stackable'] ?? false;

                $item = [
                    'name' => "{$metal} {$itemName}",
                    'description' => $this->generateDescription($metal, $itemName, $itemData['type']),
                    'type' => $itemData['type'],
                    'subtype' => $itemData['subtype'],
                    'rarity' => $tierData['rarity'],
                    'stackable' => $isStackable,
                    'required_level' => $level,
                    'base_value' => $this->calculateValue($tierData['bar_value'], $itemData['bars'], $multiplier),
                ];

                if ($isStackable) {
                    $item['max_stack'] = 1000;
                }

                if ($itemData['slot']) {
                    $item['equipment_slot'] = $itemData['slot'];
                }

                if ($itemData['atk'] > 0) {
                    $item['atk_bonus'] = (int) round($itemData['atk'] * $multiplier);
                }

                if ($itemData['str'] > 0) {
                    $item['str_bonus'] = (int) round($itemData['str'] * $multiplier);
                }

                if ($itemData['def'] > 0) {
                    $item['def_bonus'] = (int) round($itemData['def'] * $multiplier);
                }

                $items[] = $item;
            }
        }

        return $items;
    }

    /**
     * Generate a description for a smithed item.
     */
    private function generateDescription(string $metal, string $itemName, string $type): string
    {
        $metalDescriptions = [
            'Bronze' => 'A basic',
            'Iron' => 'A sturdy',
            'Steel' => 'A well-crafted',
            'Mithril' => 'A gleaming',
            'Celestial' => 'A radiant',
            'Oria' => 'A divine',
        ];

        $typeWord = $type === 'armor' ? 'piece of armor' : ($type === 'weapon' ? 'weapon' : 'item');
        $prefix = $metalDescriptions[$metal] ?? 'A';

        return "{$prefix} {$metal} {$itemName}. A formidable {$typeWord}.";
    }

    /**
     * Calculate base value for a smithed item.
     */
    private function calculateValue(int $barValue, int $bars, float $multiplier): int
    {
        return (int) round($barValue * $bars * $multiplier * 1.5);
    }

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Generate smithed items programmatically
        $smithedItems = $this->generateSmithedItems();

        $items = [
            // === LEGACY WEAPONS (kept for backwards compatibility) ===
            [
                'name' => 'Dragon Slayer',
                'description' => 'A legendary sword said to have felled dragons.',
                'type' => 'weapon',
                'subtype' => 'sword',
                'rarity' => 'legendary',
                'stackable' => false,
                'atk_bonus' => 50,
                'str_bonus' => 30,
                'equipment_slot' => 'weapon',
                'required_level' => 80,
                'effective_against' => ['dragon'],
                'base_value' => 25000,
            ],

            // === LEGACY ARMOR (kept for backwards compatibility) ===
            [
                'name' => 'Leather Cap',
                'description' => 'A simple leather cap offering minimal protection.',
                'type' => 'armor',
                'subtype' => 'helmet',
                'rarity' => 'common',
                'stackable' => false,
                'def_bonus' => 2,
                'equipment_slot' => 'head',
                'required_level' => 1,
                'base_value' => 25,
            ],
            [
                'name' => 'Leather Vest',
                'description' => 'A simple leather vest.',
                'type' => 'armor',
                'subtype' => 'chest',
                'rarity' => 'common',
                'stackable' => false,
                'def_bonus' => 4,
                'equipment_slot' => 'chest',
                'required_level' => 1,
                'base_value' => 40,
            ],
            [
                'name' => 'Wooden Shield',
                'description' => 'A basic wooden shield.',
                'type' => 'armor',
                'subtype' => 'shield',
                'rarity' => 'common',
                'stackable' => false,
                'def_bonus' => 3,
                'equipment_slot' => 'shield',
                'required_level' => 1,
                'base_value' => 30,
            ],

            // === RESOURCES ===
            // Ores
            [
                'name' => 'Copper Ore',
                'description' => 'Raw copper ore ready to be smelted.',
                'type' => 'resource',
                'subtype' => 'ore',
                'rarity' => 'common',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 5,
            ],
            [
                'name' => 'Tin Ore',
                'description' => 'Raw tin ore. Combine with copper to make bronze.',
                'type' => 'resource',
                'subtype' => 'ore',
                'rarity' => 'common',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 5,
            ],
            [
                'name' => 'Iron Ore',
                'description' => 'Raw iron ore ready to be smelted.',
                'type' => 'resource',
                'subtype' => 'ore',
                'rarity' => 'common',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 15,
            ],
            [
                'name' => 'Coal',
                'description' => 'Black coal used in smithing.',
                'type' => 'resource',
                'subtype' => 'ore',
                'rarity' => 'common',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 10,
            ],
            [
                'name' => 'Gold Ore',
                'description' => 'Valuable gold ore.',
                'type' => 'resource',
                'subtype' => 'ore',
                'rarity' => 'uncommon',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 50,
            ],
            [
                'name' => 'Mithril Ore',
                'description' => 'Rare mithril ore with a blue shimmer.',
                'type' => 'resource',
                'subtype' => 'ore',
                'rarity' => 'rare',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 200,
            ],
            [
                'name' => 'Celestial Ore',
                'description' => 'A rare ore from meteorites, pulsing with cosmic energy.',
                'type' => 'resource',
                'subtype' => 'ore',
                'rarity' => 'rare',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 500,
            ],
            [
                'name' => 'Oria Ore',
                'description' => 'The rarest and most powerful ore in existence, said to be blessed by the gods.',
                'type' => 'resource',
                'subtype' => 'ore',
                'rarity' => 'epic',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 1000,
            ],

            // Bars
            [
                'name' => 'Bronze Bar',
                'description' => 'A bar of smelted bronze.',
                'type' => 'resource',
                'subtype' => 'bar',
                'rarity' => 'common',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 15,
            ],
            [
                'name' => 'Iron Bar',
                'description' => 'A bar of smelted iron.',
                'type' => 'resource',
                'subtype' => 'bar',
                'rarity' => 'common',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 40,
            ],
            [
                'name' => 'Steel Bar',
                'description' => 'A refined bar of steel.',
                'type' => 'resource',
                'subtype' => 'bar',
                'rarity' => 'uncommon',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 100,
            ],
            [
                'name' => 'Mithril Bar',
                'description' => 'A gleaming bar of refined mithril.',
                'type' => 'resource',
                'subtype' => 'bar',
                'rarity' => 'uncommon',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 300,
            ],
            [
                'name' => 'Celestial Bar',
                'description' => 'A bar of refined celestial metal, radiating with cosmic power.',
                'type' => 'resource',
                'subtype' => 'bar',
                'rarity' => 'rare',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 800,
            ],
            [
                'name' => 'Oria Bar',
                'description' => 'The most precious metal bar, forged from divine oria ore.',
                'type' => 'resource',
                'subtype' => 'bar',
                'rarity' => 'epic',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 1500,
            ],

            // Fish (perishable - spoils after time)
            [
                'name' => 'Raw Shrimp',
                'description' => 'A small freshwater shrimp. Will spoil if not cooked.',
                'type' => 'resource',
                'subtype' => 'fish',
                'rarity' => 'common',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 3,
                'is_perishable' => true,
                'spoil_after_weeks' => 2,
                'decays_into' => 'Spoiled Food',
            ],
            [
                'name' => 'Raw Sardine',
                'description' => 'A small silvery fish. Will spoil if not cooked.',
                'type' => 'resource',
                'subtype' => 'fish',
                'rarity' => 'common',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 5,
                'is_perishable' => true,
                'spoil_after_weeks' => 2,
                'decays_into' => 'Spoiled Food',
            ],
            [
                'name' => 'Raw Trout',
                'description' => 'A freshly caught trout. Will spoil if not cooked.',
                'type' => 'resource',
                'subtype' => 'fish',
                'rarity' => 'common',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 8,
                'is_perishable' => true,
                'spoil_after_weeks' => 2,
                'decays_into' => 'Spoiled Food',
            ],
            [
                'name' => 'Raw Salmon',
                'description' => 'A freshly caught salmon. Will spoil if not cooked.',
                'type' => 'resource',
                'subtype' => 'fish',
                'rarity' => 'common',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 15,
                'is_perishable' => true,
                'spoil_after_weeks' => 2,
                'decays_into' => 'Spoiled Food',
            ],
            [
                'name' => 'Raw Lobster',
                'description' => 'A freshly caught lobster. Will spoil if not cooked.',
                'type' => 'resource',
                'subtype' => 'fish',
                'rarity' => 'uncommon',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 50,
                'is_perishable' => true,
                'spoil_after_weeks' => 2,
                'decays_into' => 'Spoiled Food',
            ],
            [
                'name' => 'Raw Swordfish',
                'description' => 'A magnificent swordfish. Will spoil if not cooked.',
                'type' => 'resource',
                'subtype' => 'fish',
                'rarity' => 'rare',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 100,
                'is_perishable' => true,
                'spoil_after_weeks' => 2,
                'decays_into' => 'Spoiled Food',
            ],

            // Grain (base food for village stockpiles - slow decay)
            [
                'name' => 'Grain',
                'description' => 'A sack of grain. The staple food of the realm. Slowly decays over time.',
                'type' => 'resource',
                'subtype' => 'grain',
                'rarity' => 'common',
                'stackable' => true,
                'max_stack' => 1000,
                'base_value' => 2,
                'is_perishable' => true,
                'decay_rate_per_week' => 1,
            ],
            [
                'name' => 'Flour',
                'description' => 'Ground flour from grain. Used for baking bread and pies.',
                'type' => 'resource',
                'subtype' => 'grain',
                'rarity' => 'common',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 5,
            ],
            [
                'name' => 'Raw Meat',
                'description' => 'Fresh raw meat from hunting. Will spoil if not cooked.',
                'type' => 'resource',
                'subtype' => 'meat',
                'rarity' => 'common',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 12,
                'is_perishable' => true,
                'spoil_after_weeks' => 2,
                'decays_into' => 'Spoiled Food',
            ],
            [
                'name' => 'Wood',
                'description' => 'A bundle of common wood logs.',
                'type' => 'resource',
                'subtype' => 'wood',
                'rarity' => 'common',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 3,
            ],
            [
                'name' => 'Oak Wood',
                'description' => 'Sturdy oak logs, good for construction.',
                'type' => 'resource',
                'subtype' => 'wood',
                'rarity' => 'common',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 8,
            ],
            [
                'name' => 'Willow Wood',
                'description' => 'Flexible willow logs, good for bows and fishing rods.',
                'type' => 'resource',
                'subtype' => 'wood',
                'rarity' => 'common',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 6,
            ],

            // Herbs (herblore gathering)
            [
                'name' => 'Herb',
                'description' => 'A common herb with mild properties.',
                'type' => 'resource',
                'subtype' => 'herb',
                'rarity' => 'common',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 2,
            ],
            [
                'name' => 'Healing Herb',
                'description' => 'A herb known for its healing properties.',
                'type' => 'resource',
                'subtype' => 'herb',
                'rarity' => 'common',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 5,
            ],
            [
                'name' => 'Moonpetal',
                'description' => 'A luminescent flower that blooms at night.',
                'type' => 'resource',
                'subtype' => 'herb',
                'rarity' => 'uncommon',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 15,
            ],
            [
                'name' => 'Bloodroot',
                'description' => 'A deep red root with potent alchemical uses.',
                'type' => 'resource',
                'subtype' => 'herb',
                'rarity' => 'uncommon',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 25,
            ],
            [
                'name' => 'Ghostcap Mushroom',
                'description' => 'A pale, ethereal mushroom found in dark places.',
                'type' => 'resource',
                'subtype' => 'herb',
                'rarity' => 'rare',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 50,
            ],
            [
                'name' => 'Dragonvine',
                'description' => 'A legendary plant said to grow where dragons once slept.',
                'type' => 'resource',
                'subtype' => 'herb',
                'rarity' => 'epic',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 100,
            ],

            // Additional herbs and ingredients for apothecary
            [
                'name' => 'Nightshade',
                'description' => 'A dark purple plant with potent properties. Handle with care.',
                'type' => 'resource',
                'subtype' => 'herb',
                'rarity' => 'uncommon',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 20,
            ],
            [
                'name' => 'Sunblossom',
                'description' => 'A bright yellow flower that only blooms at midday.',
                'type' => 'resource',
                'subtype' => 'herb',
                'rarity' => 'common',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 8,
            ],
            [
                'name' => 'Stoneroot',
                'description' => 'A tough, hardy root found near rocky outcrops.',
                'type' => 'resource',
                'subtype' => 'herb',
                'rarity' => 'common',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 10,
            ],
            [
                'name' => 'Ironbark',
                'description' => 'Bark from the rare ironwood tree, as hard as metal.',
                'type' => 'resource',
                'subtype' => 'herb',
                'rarity' => 'uncommon',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 18,
            ],
            [
                'name' => 'Hawkeye Leaf',
                'description' => 'A leaf said to sharpen one\'s sight and focus.',
                'type' => 'resource',
                'subtype' => 'herb',
                'rarity' => 'uncommon',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 22,
            ],
            [
                'name' => 'Swiftfoot Moss',
                'description' => 'A soft moss that grows in swift-flowing streams.',
                'type' => 'resource',
                'subtype' => 'herb',
                'rarity' => 'uncommon',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 25,
            ],
            [
                'name' => 'Windweed',
                'description' => 'A wispy plant that seems to blow even without wind.',
                'type' => 'resource',
                'subtype' => 'herb',
                'rarity' => 'uncommon',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 20,
            ],
            [
                'name' => 'Starlight Essence',
                'description' => 'A rare essence collected from dew under starlight.',
                'type' => 'resource',
                'subtype' => 'essence',
                'rarity' => 'rare',
                'stackable' => true,
                'max_stack' => 50,
                'base_value' => 150,
            ],
            [
                'name' => 'Void Essence',
                'description' => 'A mysterious dark essence from the void between realms.',
                'type' => 'resource',
                'subtype' => 'essence',
                'rarity' => 'epic',
                'stackable' => true,
                'max_stack' => 20,
                'base_value' => 500,
            ],

            // Monster drops for potions
            [
                'name' => 'Venom Sac',
                'description' => 'A venom sac from a poisonous creature.',
                'type' => 'resource',
                'subtype' => 'monster_part',
                'rarity' => 'uncommon',
                'stackable' => true,
                'max_stack' => 50,
                'base_value' => 35,
            ],
            [
                'name' => 'Giant Essence',
                'description' => 'The essence of a giant\'s strength.',
                'type' => 'resource',
                'subtype' => 'essence',
                'rarity' => 'uncommon',
                'stackable' => true,
                'max_stack' => 50,
                'base_value' => 45,
            ],
            [
                'name' => 'Turtle Shell Powder',
                'description' => 'Ground turtle shell, known for its protective properties.',
                'type' => 'resource',
                'subtype' => 'monster_part',
                'rarity' => 'uncommon',
                'stackable' => true,
                'max_stack' => 50,
                'base_value' => 40,
            ],
            [
                'name' => 'Phoenix Feather',
                'description' => 'A radiant feather from the legendary phoenix.',
                'type' => 'resource',
                'subtype' => 'monster_part',
                'rarity' => 'rare',
                'stackable' => true,
                'max_stack' => 20,
                'base_value' => 200,
            ],
            [
                'name' => 'Unicorn Tears',
                'description' => 'Sacred tears from a unicorn, with miraculous healing properties.',
                'type' => 'resource',
                'subtype' => 'essence',
                'rarity' => 'epic',
                'stackable' => true,
                'max_stack' => 10,
                'base_value' => 1000,
            ],
            [
                'name' => 'Holy Water',
                'description' => 'Water blessed by priests, imbued with divine energy.',
                'type' => 'resource',
                'subtype' => 'essence',
                'rarity' => 'uncommon',
                'stackable' => true,
                'max_stack' => 50,
                'base_value' => 30,
            ],

            // Vials for potion crafting
            [
                'name' => 'Vial',
                'description' => 'A small glass vial for holding potions.',
                'type' => 'misc',
                'subtype' => 'container',
                'rarity' => 'common',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 5,
            ],
            [
                'name' => 'Crystal Vial',
                'description' => 'A high-quality crystal vial for potent potions.',
                'type' => 'misc',
                'subtype' => 'container',
                'rarity' => 'uncommon',
                'stackable' => true,
                'max_stack' => 50,
                'base_value' => 25,
            ],

            // Spoiled Food (result of decay)
            [
                'name' => 'Spoiled Food',
                'description' => 'Rotten food that is no longer edible. Can be used as compost.',
                'type' => 'misc',
                'subtype' => 'waste',
                'rarity' => 'common',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 0,
            ],

            // === CONSUMABLES ===
            // Food (cooked food lasts longer but still perishable)
            [
                'name' => 'Cooked Shrimp',
                'description' => 'A cooked shrimp. Heals 3 HP. Lasts longer than raw shrimp.',
                'type' => 'consumable',
                'subtype' => 'food',
                'rarity' => 'common',
                'stackable' => true,
                'max_stack' => 50,
                'hp_bonus' => 3,
                'base_value' => 8,
                'is_perishable' => true,
                'spoil_after_weeks' => 4,
                'decays_into' => 'Spoiled Food',
            ],
            [
                'name' => 'Bread',
                'description' => 'A loaf of freshly baked bread. Heals 5 HP. Will go stale over time.',
                'type' => 'consumable',
                'subtype' => 'food',
                'rarity' => 'common',
                'stackable' => true,
                'max_stack' => 50,
                'hp_bonus' => 5,
                'base_value' => 10,
                'is_perishable' => true,
                'spoil_after_weeks' => 4,
                'decays_into' => 'Spoiled Food',
            ],
            [
                'name' => 'Cooked Trout',
                'description' => 'A cooked trout. Heals 10 HP. Lasts longer than raw fish.',
                'type' => 'consumable',
                'subtype' => 'food',
                'rarity' => 'common',
                'stackable' => true,
                'max_stack' => 50,
                'hp_bonus' => 10,
                'base_value' => 20,
                'is_perishable' => true,
                'spoil_after_weeks' => 4,
                'decays_into' => 'Spoiled Food',
            ],
            [
                'name' => 'Cooked Salmon',
                'description' => 'A cooked salmon. Heals 15 HP. Lasts longer than raw fish.',
                'type' => 'consumable',
                'subtype' => 'food',
                'rarity' => 'common',
                'stackable' => true,
                'max_stack' => 50,
                'hp_bonus' => 15,
                'base_value' => 35,
                'is_perishable' => true,
                'spoil_after_weeks' => 4,
                'decays_into' => 'Spoiled Food',
            ],
            [
                'name' => 'Cooked Lobster',
                'description' => 'A delicious cooked lobster. Heals 25 HP. Lasts longer than raw lobster.',
                'type' => 'consumable',
                'subtype' => 'food',
                'rarity' => 'uncommon',
                'stackable' => true,
                'max_stack' => 50,
                'hp_bonus' => 25,
                'base_value' => 100,
                'is_perishable' => true,
                'spoil_after_weeks' => 4,
                'decays_into' => 'Spoiled Food',
            ],
            [
                'name' => 'Meat Pie',
                'description' => 'A hearty meat pie. Heals 20 HP. Preserves well.',
                'type' => 'consumable',
                'subtype' => 'food',
                'rarity' => 'common',
                'stackable' => true,
                'max_stack' => 50,
                'hp_bonus' => 20,
                'base_value' => 50,
                'is_perishable' => true,
                'spoil_after_weeks' => 6,
                'decays_into' => 'Spoiled Food',
            ],
            [
                'name' => 'Cooked Meat',
                'description' => 'A cooked piece of meat. Heals 12 HP.',
                'type' => 'consumable',
                'subtype' => 'food',
                'rarity' => 'common',
                'stackable' => true,
                'max_stack' => 50,
                'hp_bonus' => 12,
                'base_value' => 25,
                'is_perishable' => true,
                'spoil_after_weeks' => 4,
                'decays_into' => 'Spoiled Food',
            ],

            // Potions
            [
                'name' => 'Minor Health Potion',
                'description' => 'A small red potion. Heals 15 HP instantly.',
                'type' => 'consumable',
                'subtype' => 'potion',
                'rarity' => 'common',
                'stackable' => true,
                'max_stack' => 20,
                'hp_bonus' => 15,
                'base_value' => 30,
            ],
            [
                'name' => 'Health Potion',
                'description' => 'A red potion. Heals 30 HP instantly.',
                'type' => 'consumable',
                'subtype' => 'potion',
                'rarity' => 'uncommon',
                'stackable' => true,
                'max_stack' => 20,
                'hp_bonus' => 30,
                'base_value' => 75,
            ],
            [
                'name' => 'Greater Health Potion',
                'description' => 'A large red potion. Heals 50 HP instantly.',
                'type' => 'consumable',
                'subtype' => 'potion',
                'rarity' => 'rare',
                'stackable' => true,
                'max_stack' => 20,
                'hp_bonus' => 50,
                'base_value' => 200,
            ],
            [
                'name' => 'Energy Elixir',
                'description' => 'A yellow potion that restores 10 energy.',
                'type' => 'consumable',
                'subtype' => 'potion',
                'rarity' => 'rare',
                'stackable' => true,
                'max_stack' => 10,
                'energy_bonus' => 10,
                'base_value' => 500,
            ],
            [
                'name' => 'Energy Tonic',
                'description' => 'A refreshing tonic that restores 5 energy.',
                'type' => 'consumable',
                'subtype' => 'potion',
                'rarity' => 'uncommon',
                'stackable' => true,
                'max_stack' => 20,
                'energy_bonus' => 5,
                'base_value' => 150,
            ],

            // Combat potions
            [
                'name' => 'Attack Potion',
                'description' => 'Temporarily boosts attack by 10%. Lasts 5 minutes.',
                'type' => 'consumable',
                'subtype' => 'potion',
                'rarity' => 'uncommon',
                'stackable' => true,
                'max_stack' => 20,
                'buff_type' => 'attack',
                'buff_percent' => 10,
                'buff_duration' => 300,
                'base_value' => 100,
            ],
            [
                'name' => 'Strength Potion',
                'description' => 'Temporarily boosts strength by 10%. Lasts 5 minutes.',
                'type' => 'consumable',
                'subtype' => 'potion',
                'rarity' => 'uncommon',
                'stackable' => true,
                'max_stack' => 20,
                'buff_type' => 'strength',
                'buff_percent' => 10,
                'buff_duration' => 300,
                'base_value' => 100,
            ],
            [
                'name' => 'Defense Potion',
                'description' => 'Temporarily boosts defense by 10%. Lasts 5 minutes.',
                'type' => 'consumable',
                'subtype' => 'potion',
                'rarity' => 'uncommon',
                'stackable' => true,
                'max_stack' => 20,
                'buff_type' => 'defense',
                'buff_percent' => 10,
                'buff_duration' => 300,
                'base_value' => 100,
            ],
            [
                'name' => 'Accuracy Potion',
                'description' => 'Temporarily boosts hit chance by 10%. Lasts 5 minutes.',
                'type' => 'consumable',
                'subtype' => 'potion',
                'rarity' => 'uncommon',
                'stackable' => true,
                'max_stack' => 20,
                'buff_type' => 'accuracy',
                'buff_percent' => 10,
                'buff_duration' => 300,
                'base_value' => 120,
            ],
            [
                'name' => 'Agility Potion',
                'description' => 'Temporarily boosts dodge chance by 10%. Lasts 5 minutes.',
                'type' => 'consumable',
                'subtype' => 'potion',
                'rarity' => 'uncommon',
                'stackable' => true,
                'max_stack' => 20,
                'buff_type' => 'agility',
                'buff_percent' => 10,
                'buff_duration' => 300,
                'base_value' => 130,
            ],
            [
                'name' => 'Super Attack Potion',
                'description' => 'Greatly boosts attack by 20%. Lasts 5 minutes.',
                'type' => 'consumable',
                'subtype' => 'potion',
                'rarity' => 'rare',
                'stackable' => true,
                'max_stack' => 10,
                'buff_type' => 'attack',
                'buff_percent' => 20,
                'buff_duration' => 300,
                'base_value' => 300,
            ],
            [
                'name' => 'Super Strength Potion',
                'description' => 'Greatly boosts strength by 20%. Lasts 5 minutes.',
                'type' => 'consumable',
                'subtype' => 'potion',
                'rarity' => 'rare',
                'stackable' => true,
                'max_stack' => 10,
                'buff_type' => 'strength',
                'buff_percent' => 20,
                'buff_duration' => 300,
                'base_value' => 300,
            ],
            [
                'name' => 'Super Defense Potion',
                'description' => 'Greatly boosts defense by 20%. Lasts 5 minutes.',
                'type' => 'consumable',
                'subtype' => 'potion',
                'rarity' => 'rare',
                'stackable' => true,
                'max_stack' => 10,
                'buff_type' => 'defense',
                'buff_percent' => 20,
                'buff_duration' => 300,
                'base_value' => 300,
            ],
            [
                'name' => 'Prayer Potion',
                'description' => 'Restores 30 prayer points.',
                'type' => 'consumable',
                'subtype' => 'potion',
                'rarity' => 'rare',
                'stackable' => true,
                'max_stack' => 10,
                'prayer_bonus' => 30,
                'base_value' => 250,
            ],
            [
                'name' => 'Combat Potion',
                'description' => 'Boosts attack, strength, and defense by 15%. Lasts 5 minutes.',
                'type' => 'consumable',
                'subtype' => 'potion',
                'rarity' => 'rare',
                'stackable' => true,
                'max_stack' => 10,
                'buff_type' => 'combat',
                'buff_percent' => 15,
                'buff_duration' => 300,
                'base_value' => 500,
            ],
            [
                'name' => 'Overload Potion',
                'description' => 'Massively boosts all combat stats by 25%. Lasts 5 minutes.',
                'type' => 'consumable',
                'subtype' => 'potion',
                'rarity' => 'epic',
                'stackable' => true,
                'max_stack' => 5,
                'buff_type' => 'overload',
                'buff_percent' => 25,
                'buff_duration' => 300,
                'base_value' => 1500,
            ],
            [
                'name' => 'Elixir of Life',
                'description' => 'A legendary elixir that fully restores HP and provides regeneration.',
                'type' => 'consumable',
                'subtype' => 'potion',
                'rarity' => 'legendary',
                'stackable' => true,
                'max_stack' => 3,
                'hp_bonus' => 100,
                'buff_type' => 'regeneration',
                'buff_percent' => 5,
                'buff_duration' => 600,
                'base_value' => 5000,
            ],

            // Medical supplies
            [
                'name' => 'Bandage',
                'description' => 'Clean linen bandages for treating wounds. Heals 8 HP.',
                'type' => 'consumable',
                'subtype' => 'medical',
                'rarity' => 'common',
                'stackable' => true,
                'max_stack' => 50,
                'hp_bonus' => 8,
                'base_value' => 10,
            ],
            [
                'name' => 'Medicine',
                'description' => 'Herbal medicine that speeds recovery. Heals 20 HP.',
                'type' => 'consumable',
                'subtype' => 'medical',
                'rarity' => 'uncommon',
                'stackable' => true,
                'max_stack' => 20,
                'hp_bonus' => 20,
                'base_value' => 50,
            ],
            [
                'name' => 'Antidote',
                'description' => 'Cures poison and removes toxins from the body.',
                'type' => 'consumable',
                'subtype' => 'medical',
                'rarity' => 'uncommon',
                'stackable' => true,
                'max_stack' => 20,
                'base_value' => 75,
            ],
            [
                'name' => 'Healing Potion',
                'description' => 'A potent healing draught prepared by a physician. Heals 40 HP.',
                'type' => 'consumable',
                'subtype' => 'medical',
                'rarity' => 'rare',
                'stackable' => true,
                'max_stack' => 10,
                'hp_bonus' => 40,
                'base_value' => 150,
            ],

            // Feast items
            [
                'name' => 'Feast Platter',
                'description' => 'A grand platter of assorted meats, cheeses, and delicacies. Heals 50 HP and provides a temporary buff.',
                'type' => 'consumable',
                'subtype' => 'food',
                'rarity' => 'rare',
                'stackable' => true,
                'max_stack' => 5,
                'hp_bonus' => 50,
                'base_value' => 200,
            ],

            // === TOOLS ===
            [
                'name' => 'Bronze Pickaxe',
                'description' => 'A basic pickaxe for mining.',
                'type' => 'tool',
                'subtype' => 'pickaxe',
                'rarity' => 'common',
                'stackable' => false,
                'equipment_slot' => 'weapon',
                'required_skill' => 'mining',
                'required_skill_level' => 1,
                'base_value' => 40,
            ],
            [
                'name' => 'Iron Pickaxe',
                'description' => 'An iron pickaxe for efficient mining.',
                'type' => 'tool',
                'subtype' => 'pickaxe',
                'rarity' => 'common',
                'stackable' => false,
                'equipment_slot' => 'weapon',
                'required_skill' => 'mining',
                'required_skill_level' => 10,
                'base_value' => 150,
            ],
            [
                'name' => 'Steel Pickaxe',
                'description' => 'A high-quality steel pickaxe.',
                'type' => 'tool',
                'subtype' => 'pickaxe',
                'rarity' => 'uncommon',
                'stackable' => false,
                'equipment_slot' => 'weapon',
                'required_skill' => 'mining',
                'required_skill_level' => 30,
                'base_value' => 500,
            ],
            [
                'name' => 'Fishing Rod',
                'description' => 'A basic fishing rod.',
                'type' => 'tool',
                'subtype' => 'fishing',
                'rarity' => 'common',
                'stackable' => false,
                'required_skill' => 'fishing',
                'required_skill_level' => 1,
                'base_value' => 25,
            ],
            [
                'name' => 'Fishing Net',
                'description' => 'A net for catching small fish.',
                'type' => 'tool',
                'subtype' => 'fishing',
                'rarity' => 'common',
                'stackable' => false,
                'required_skill' => 'fishing',
                'required_skill_level' => 5,
                'base_value' => 50,
            ],
            [
                'name' => 'Hammer',
                'description' => 'A smithing hammer for metalwork.',
                'type' => 'tool',
                'subtype' => 'smithing',
                'rarity' => 'common',
                'stackable' => false,
                'required_skill' => 'smithing',
                'required_skill_level' => 1,
                'base_value' => 30,
            ],
            [
                'name' => 'Needle',
                'description' => 'A needle for crafting.',
                'type' => 'tool',
                'subtype' => 'crafting',
                'rarity' => 'common',
                'stackable' => false,
                'required_skill' => 'crafting',
                'required_skill_level' => 1,
                'base_value' => 5,
            ],

            // === MISC ===
            [
                'name' => 'Nails',
                'description' => 'Metal nails for construction and crafting.',
                'type' => 'misc',
                'subtype' => 'material',
                'rarity' => 'common',
                'stackable' => true,
                'max_stack' => 500,
                'base_value' => 1,
            ],
            [
                'name' => 'Oak Plank',
                'description' => 'A sturdy oak plank for construction.',
                'type' => 'misc',
                'subtype' => 'material',
                'rarity' => 'common',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 20,
            ],
            [
                'name' => 'Wooden Arrow',
                'description' => 'A simple wooden arrow for ranged combat.',
                'type' => 'misc',
                'subtype' => 'ammunition',
                'rarity' => 'common',
                'stackable' => true,
                'max_stack' => 1000,
                'base_value' => 2,
            ],
            [
                'name' => 'Bones',
                'description' => 'Bones from a defeated creature.',
                'type' => 'misc',
                'subtype' => 'remains',
                'rarity' => 'common',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 2,
            ],
            [
                'name' => 'Big Bones',
                'description' => 'Large bones from a powerful creature.',
                'type' => 'misc',
                'subtype' => 'remains',
                'rarity' => 'uncommon',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 15,
            ],
            [
                'name' => 'Dragon Bones',
                'description' => 'Rare bones from a slain dragon.',
                'type' => 'misc',
                'subtype' => 'remains',
                'rarity' => 'rare',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 500,
            ],
            [
                'name' => 'Thread',
                'description' => 'A spool of thread for crafting.',
                'type' => 'misc',
                'subtype' => 'material',
                'rarity' => 'common',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 3,
            ],
            [
                'name' => 'Leather',
                'description' => 'Tanned leather for crafting.',
                'type' => 'misc',
                'subtype' => 'material',
                'rarity' => 'common',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 10,
            ],

            // === CROP HARVESTS (from farming) ===
            [
                'name' => 'Wheat',
                'description' => 'Freshly harvested wheat. Can be milled into flour or donated to the village granary.',
                'type' => 'resource',
                'subtype' => 'crop',
                'rarity' => 'common',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 3,
            ],
            [
                'name' => 'Potatoes',
                'description' => 'Fresh potatoes from the farm. Nutritious and filling.',
                'type' => 'consumable',
                'subtype' => 'food',
                'rarity' => 'common',
                'stackable' => true,
                'max_stack' => 50,
                'hp_bonus' => 5,
                'base_value' => 4,
            ],
            [
                'name' => 'Carrots',
                'description' => 'Crunchy orange carrots. Good for stews or horse feed.',
                'type' => 'consumable',
                'subtype' => 'food',
                'rarity' => 'common',
                'stackable' => true,
                'max_stack' => 50,
                'hp_bonus' => 4,
                'base_value' => 5,
            ],
            [
                'name' => 'Cabbage',
                'description' => 'Fresh leafy cabbage. Perfect for soups and salads.',
                'type' => 'consumable',
                'subtype' => 'food',
                'rarity' => 'common',
                'stackable' => true,
                'max_stack' => 50,
                'hp_bonus' => 6,
                'base_value' => 6,
            ],
            [
                'name' => 'Onions',
                'description' => 'Pungent onions used in countless recipes.',
                'type' => 'resource',
                'subtype' => 'crop',
                'rarity' => 'common',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 5,
            ],
            [
                'name' => 'Corn',
                'description' => 'Golden ears of corn. Great for feed and flour.',
                'type' => 'consumable',
                'subtype' => 'food',
                'rarity' => 'common',
                'stackable' => true,
                'max_stack' => 50,
                'hp_bonus' => 8,
                'base_value' => 8,
            ],
            [
                'name' => 'Tomatoes',
                'description' => 'Ripe red tomatoes that brighten any dish.',
                'type' => 'consumable',
                'subtype' => 'food',
                'rarity' => 'common',
                'stackable' => true,
                'max_stack' => 50,
                'hp_bonus' => 6,
                'base_value' => 7,
            ],
            [
                'name' => 'Pumpkins',
                'description' => 'Large orange gourds. Festive and nutritious.',
                'type' => 'consumable',
                'subtype' => 'food',
                'rarity' => 'uncommon',
                'stackable' => true,
                'max_stack' => 50,
                'hp_bonus' => 12,
                'base_value' => 15,
            ],
            [
                'name' => 'Grapes',
                'description' => 'Sweet grape clusters perfect for wine making.',
                'type' => 'resource',
                'subtype' => 'crop',
                'rarity' => 'uncommon',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 12,
            ],
            [
                'name' => 'Hops',
                'description' => 'Essential ingredient for brewing fine ales.',
                'type' => 'resource',
                'subtype' => 'crop',
                'rarity' => 'uncommon',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 10,
            ],
            [
                'name' => 'Farm Herbs',
                'description' => 'Aromatic herbs used in cooking and medicine.',
                'type' => 'resource',
                'subtype' => 'herb',
                'rarity' => 'common',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 6,
            ],
            [
                'name' => 'Flax',
                'description' => 'Blue-flowered plant used for linen and oil.',
                'type' => 'resource',
                'subtype' => 'crop',
                'rarity' => 'uncommon',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 12,
            ],

            // Rings and Amulets
            [
                'name' => 'Gold Ring',
                'description' => 'A simple gold ring.',
                'type' => 'armor',
                'subtype' => 'ring',
                'rarity' => 'uncommon',
                'stackable' => false,
                'equipment_slot' => 'ring',
                'base_value' => 200,
            ],
            [
                'name' => 'Ring of Strength',
                'description' => 'A ring imbued with strengthening magic.',
                'type' => 'armor',
                'subtype' => 'ring',
                'rarity' => 'rare',
                'stackable' => false,
                'str_bonus' => 5,
                'equipment_slot' => 'ring',
                'required_level' => 20,
                'base_value' => 1000,
            ],
            [
                'name' => 'Amulet of Defense',
                'description' => 'An amulet that provides protection.',
                'type' => 'armor',
                'subtype' => 'amulet',
                'rarity' => 'rare',
                'stackable' => false,
                'def_bonus' => 5,
                'equipment_slot' => 'amulet',
                'required_level' => 20,
                'base_value' => 1000,
            ],
            [
                'name' => 'Amulet of Power',
                'description' => 'A legendary amulet radiating power.',
                'type' => 'armor',
                'subtype' => 'amulet',
                'rarity' => 'epic',
                'stackable' => false,
                'atk_bonus' => 10,
                'str_bonus' => 10,
                'def_bonus' => 10,
                'equipment_slot' => 'amulet',
                'required_level' => 60,
                'base_value' => 10000,
            ],
        ];

        // Merge smithed items with other items
        $allItems = array_merge($smithedItems, $items);

        foreach ($allItems as $item) {
            Item::updateOrCreate(
                ['name' => $item['name']],
                $item
            );
        }
    }
}
