<?php

namespace Database\Seeders;

use App\Models\Item;
use Illuminate\Database\Seeder;

class ItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $items = [
            // === WEAPONS ===
            // Daggers
            [
                'name' => 'Bronze Dagger',
                'description' => 'A small but quick bronze dagger.',
                'type' => 'weapon',
                'subtype' => 'dagger',
                'rarity' => 'common',
                'stackable' => false,
                'atk_bonus' => 3,
                'str_bonus' => 1,
                'equipment_slot' => 'weapon',
                'required_level' => 1,
                'base_value' => 35,
            ],
            [
                'name' => 'Iron Dagger',
                'description' => 'A sharp iron dagger.',
                'type' => 'weapon',
                'subtype' => 'dagger',
                'rarity' => 'common',
                'stackable' => false,
                'atk_bonus' => 6,
                'str_bonus' => 2,
                'equipment_slot' => 'weapon',
                'required_level' => 5,
                'base_value' => 80,
            ],

            // Swords
            [
                'name' => 'Bronze Sword',
                'description' => 'A basic sword forged from bronze.',
                'type' => 'weapon',
                'subtype' => 'sword',
                'rarity' => 'common',
                'stackable' => false,
                'atk_bonus' => 4,
                'str_bonus' => 2,
                'equipment_slot' => 'weapon',
                'required_level' => 1,
                'base_value' => 50,
            ],
            [
                'name' => 'Iron Sword',
                'description' => 'A sturdy sword made of iron.',
                'type' => 'weapon',
                'subtype' => 'sword',
                'rarity' => 'common',
                'stackable' => false,
                'atk_bonus' => 8,
                'str_bonus' => 4,
                'equipment_slot' => 'weapon',
                'required_level' => 10,
                'base_value' => 150,
            ],
            [
                'name' => 'Steel Sword',
                'description' => 'A well-crafted steel blade.',
                'type' => 'weapon',
                'subtype' => 'sword',
                'rarity' => 'uncommon',
                'stackable' => false,
                'atk_bonus' => 15,
                'str_bonus' => 8,
                'equipment_slot' => 'weapon',
                'required_level' => 25,
                'base_value' => 500,
            ],
            [
                'name' => 'Mithril Blade',
                'description' => 'A gleaming blade forged from rare mithril.',
                'type' => 'weapon',
                'subtype' => 'sword',
                'rarity' => 'rare',
                'stackable' => false,
                'atk_bonus' => 25,
                'str_bonus' => 15,
                'equipment_slot' => 'weapon',
                'required_level' => 50,
                'base_value' => 2500,
            ],
            [
                'name' => 'Dragon Slayer',
                'description' => 'A legendary sword said to have felled dragons.',
                'type' => 'weapon',
                'subtype' => 'sword',
                'rarity' => 'legendary',
                'stackable' => false,
                'atk_bonus' => 50,
                'str_bonus' => 30,
                'equipment_slot' => 'weapon',
                'required_level' => 80,
                'effective_against' => ['dragon'],
                'base_value' => 25000,
            ],

            // Axes
            [
                'name' => 'Bronze Axe',
                'description' => 'A bronze axe good for combat and woodcutting.',
                'type' => 'weapon',
                'subtype' => 'axe',
                'rarity' => 'common',
                'stackable' => false,
                'atk_bonus' => 3,
                'str_bonus' => 5,
                'equipment_slot' => 'weapon',
                'required_level' => 1,
                'base_value' => 60,
            ],
            [
                'name' => 'Iron Battleaxe',
                'description' => 'A heavy iron battleaxe.',
                'type' => 'weapon',
                'subtype' => 'axe',
                'rarity' => 'common',
                'stackable' => false,
                'atk_bonus' => 6,
                'str_bonus' => 10,
                'equipment_slot' => 'weapon',
                'required_level' => 15,
                'base_value' => 200,
            ],

            // === ARMOR ===
            // Helmets
            [
                'name' => 'Leather Cap',
                'description' => 'A simple leather cap offering minimal protection.',
                'type' => 'armor',
                'subtype' => 'helmet',
                'rarity' => 'common',
                'stackable' => false,
                'def_bonus' => 2,
                'equipment_slot' => 'head',
                'required_level' => 1,
                'base_value' => 25,
            ],
            [
                'name' => 'Iron Helm',
                'description' => 'A sturdy iron helmet.',
                'type' => 'armor',
                'subtype' => 'helmet',
                'rarity' => 'common',
                'stackable' => false,
                'def_bonus' => 6,
                'equipment_slot' => 'head',
                'required_level' => 10,
                'base_value' => 100,
            ],
            [
                'name' => 'Steel Great Helm',
                'description' => 'A full steel helm providing excellent protection.',
                'type' => 'armor',
                'subtype' => 'helmet',
                'rarity' => 'uncommon',
                'stackable' => false,
                'def_bonus' => 12,
                'equipment_slot' => 'head',
                'required_level' => 30,
                'base_value' => 400,
            ],

            // Chest armor
            [
                'name' => 'Leather Vest',
                'description' => 'A simple leather vest.',
                'type' => 'armor',
                'subtype' => 'chest',
                'rarity' => 'common',
                'stackable' => false,
                'def_bonus' => 4,
                'equipment_slot' => 'chest',
                'required_level' => 1,
                'base_value' => 40,
            ],
            [
                'name' => 'Chainmail Shirt',
                'description' => 'A shirt of interlocked iron rings.',
                'type' => 'armor',
                'subtype' => 'chest',
                'rarity' => 'common',
                'stackable' => false,
                'def_bonus' => 10,
                'equipment_slot' => 'chest',
                'required_level' => 15,
                'base_value' => 200,
            ],
            [
                'name' => 'Steel Plate Armor',
                'description' => 'Heavy plate armor forged from steel.',
                'type' => 'armor',
                'subtype' => 'chest',
                'rarity' => 'uncommon',
                'stackable' => false,
                'def_bonus' => 20,
                'hp_bonus' => 10,
                'equipment_slot' => 'chest',
                'required_level' => 40,
                'base_value' => 1000,
            ],

            // Shields
            [
                'name' => 'Wooden Shield',
                'description' => 'A basic wooden shield.',
                'type' => 'armor',
                'subtype' => 'shield',
                'rarity' => 'common',
                'stackable' => false,
                'def_bonus' => 3,
                'equipment_slot' => 'shield',
                'required_level' => 1,
                'base_value' => 30,
            ],
            [
                'name' => 'Iron Shield',
                'description' => 'A reliable iron shield.',
                'type' => 'armor',
                'subtype' => 'shield',
                'rarity' => 'common',
                'stackable' => false,
                'def_bonus' => 8,
                'equipment_slot' => 'shield',
                'required_level' => 10,
                'base_value' => 120,
            ],

            // === RESOURCES ===
            // Ores
            [
                'name' => 'Copper Ore',
                'description' => 'Raw copper ore ready to be smelted.',
                'type' => 'resource',
                'subtype' => 'ore',
                'rarity' => 'common',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 5,
            ],
            [
                'name' => 'Tin Ore',
                'description' => 'Raw tin ore. Combine with copper to make bronze.',
                'type' => 'resource',
                'subtype' => 'ore',
                'rarity' => 'common',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 5,
            ],
            [
                'name' => 'Iron Ore',
                'description' => 'Raw iron ore ready to be smelted.',
                'type' => 'resource',
                'subtype' => 'ore',
                'rarity' => 'common',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 15,
            ],
            [
                'name' => 'Coal',
                'description' => 'Black coal used in smithing.',
                'type' => 'resource',
                'subtype' => 'ore',
                'rarity' => 'common',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 10,
            ],
            [
                'name' => 'Gold Ore',
                'description' => 'Valuable gold ore.',
                'type' => 'resource',
                'subtype' => 'ore',
                'rarity' => 'uncommon',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 50,
            ],
            [
                'name' => 'Mithril Ore',
                'description' => 'Rare mithril ore with a blue shimmer.',
                'type' => 'resource',
                'subtype' => 'ore',
                'rarity' => 'rare',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 200,
            ],

            // Bars
            [
                'name' => 'Bronze Bar',
                'description' => 'A bar of smelted bronze.',
                'type' => 'resource',
                'subtype' => 'bar',
                'rarity' => 'common',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 15,
            ],
            [
                'name' => 'Iron Bar',
                'description' => 'A bar of smelted iron.',
                'type' => 'resource',
                'subtype' => 'bar',
                'rarity' => 'common',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 40,
            ],
            [
                'name' => 'Steel Bar',
                'description' => 'A refined bar of steel.',
                'type' => 'resource',
                'subtype' => 'bar',
                'rarity' => 'uncommon',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 100,
            ],

            // Fish (perishable - spoils after time)
            [
                'name' => 'Raw Trout',
                'description' => 'A freshly caught trout. Will spoil if not cooked.',
                'type' => 'resource',
                'subtype' => 'fish',
                'rarity' => 'common',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 8,
                'is_perishable' => true,
                'spoil_after_weeks' => 2,
                'decays_into' => 'Spoiled Food',
            ],
            [
                'name' => 'Raw Salmon',
                'description' => 'A freshly caught salmon. Will spoil if not cooked.',
                'type' => 'resource',
                'subtype' => 'fish',
                'rarity' => 'common',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 15,
                'is_perishable' => true,
                'spoil_after_weeks' => 2,
                'decays_into' => 'Spoiled Food',
            ],
            [
                'name' => 'Raw Lobster',
                'description' => 'A freshly caught lobster. Will spoil if not cooked.',
                'type' => 'resource',
                'subtype' => 'fish',
                'rarity' => 'uncommon',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 50,
                'is_perishable' => true,
                'spoil_after_weeks' => 2,
                'decays_into' => 'Spoiled Food',
            ],

            // Grain (base food for village stockpiles - slow decay)
            [
                'name' => 'Grain',
                'description' => 'A sack of grain. The staple food of the realm. Slowly decays over time.',
                'type' => 'resource',
                'subtype' => 'grain',
                'rarity' => 'common',
                'stackable' => true,
                'max_stack' => 1000,
                'base_value' => 2,
                'is_perishable' => true,
                'decay_rate_per_week' => 1,
            ],
            [
                'name' => 'Flour',
                'description' => 'Ground flour from grain. Used for baking bread and pies.',
                'type' => 'resource',
                'subtype' => 'grain',
                'rarity' => 'common',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 5,
            ],
            [
                'name' => 'Raw Meat',
                'description' => 'Fresh raw meat from hunting. Will spoil if not cooked.',
                'type' => 'resource',
                'subtype' => 'meat',
                'rarity' => 'common',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 12,
                'is_perishable' => true,
                'spoil_after_weeks' => 2,
                'decays_into' => 'Spoiled Food',
            ],
            [
                'name' => 'Wood',
                'description' => 'A bundle of common wood logs.',
                'type' => 'resource',
                'subtype' => 'wood',
                'rarity' => 'common',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 3,
            ],
            [
                'name' => 'Oak Wood',
                'description' => 'Sturdy oak logs, good for construction.',
                'type' => 'resource',
                'subtype' => 'wood',
                'rarity' => 'common',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 8,
            ],
            [
                'name' => 'Willow Wood',
                'description' => 'Flexible willow logs, good for bows and fishing rods.',
                'type' => 'resource',
                'subtype' => 'wood',
                'rarity' => 'common',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 6,
            ],

            // Spoiled Food (result of decay)
            [
                'name' => 'Spoiled Food',
                'description' => 'Rotten food that is no longer edible. Can be used as compost.',
                'type' => 'misc',
                'subtype' => 'waste',
                'rarity' => 'common',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 0,
            ],

            // === CONSUMABLES ===
            // Food (cooked food lasts longer but still perishable)
            [
                'name' => 'Bread',
                'description' => 'A loaf of freshly baked bread. Heals 5 HP. Will go stale over time.',
                'type' => 'consumable',
                'subtype' => 'food',
                'rarity' => 'common',
                'stackable' => true,
                'max_stack' => 50,
                'hp_bonus' => 5,
                'base_value' => 10,
                'is_perishable' => true,
                'spoil_after_weeks' => 4,
                'decays_into' => 'Spoiled Food',
            ],
            [
                'name' => 'Cooked Trout',
                'description' => 'A cooked trout. Heals 10 HP. Lasts longer than raw fish.',
                'type' => 'consumable',
                'subtype' => 'food',
                'rarity' => 'common',
                'stackable' => true,
                'max_stack' => 50,
                'hp_bonus' => 10,
                'base_value' => 20,
                'is_perishable' => true,
                'spoil_after_weeks' => 4,
                'decays_into' => 'Spoiled Food',
            ],
            [
                'name' => 'Cooked Salmon',
                'description' => 'A cooked salmon. Heals 15 HP. Lasts longer than raw fish.',
                'type' => 'consumable',
                'subtype' => 'food',
                'rarity' => 'common',
                'stackable' => true,
                'max_stack' => 50,
                'hp_bonus' => 15,
                'base_value' => 35,
                'is_perishable' => true,
                'spoil_after_weeks' => 4,
                'decays_into' => 'Spoiled Food',
            ],
            [
                'name' => 'Cooked Lobster',
                'description' => 'A delicious cooked lobster. Heals 25 HP. Lasts longer than raw lobster.',
                'type' => 'consumable',
                'subtype' => 'food',
                'rarity' => 'uncommon',
                'stackable' => true,
                'max_stack' => 50,
                'hp_bonus' => 25,
                'base_value' => 100,
                'is_perishable' => true,
                'spoil_after_weeks' => 4,
                'decays_into' => 'Spoiled Food',
            ],
            [
                'name' => 'Meat Pie',
                'description' => 'A hearty meat pie. Heals 20 HP. Preserves well.',
                'type' => 'consumable',
                'subtype' => 'food',
                'rarity' => 'common',
                'stackable' => true,
                'max_stack' => 50,
                'hp_bonus' => 20,
                'base_value' => 50,
                'is_perishable' => true,
                'spoil_after_weeks' => 6,
                'decays_into' => 'Spoiled Food',
            ],
            [
                'name' => 'Cooked Meat',
                'description' => 'A cooked piece of meat. Heals 12 HP.',
                'type' => 'consumable',
                'subtype' => 'food',
                'rarity' => 'common',
                'stackable' => true,
                'max_stack' => 50,
                'hp_bonus' => 12,
                'base_value' => 25,
                'is_perishable' => true,
                'spoil_after_weeks' => 4,
                'decays_into' => 'Spoiled Food',
            ],

            // Potions
            [
                'name' => 'Minor Health Potion',
                'description' => 'A small red potion. Heals 15 HP instantly.',
                'type' => 'consumable',
                'subtype' => 'potion',
                'rarity' => 'common',
                'stackable' => true,
                'max_stack' => 20,
                'hp_bonus' => 15,
                'base_value' => 30,
            ],
            [
                'name' => 'Health Potion',
                'description' => 'A red potion. Heals 30 HP instantly.',
                'type' => 'consumable',
                'subtype' => 'potion',
                'rarity' => 'uncommon',
                'stackable' => true,
                'max_stack' => 20,
                'hp_bonus' => 30,
                'base_value' => 75,
            ],
            [
                'name' => 'Greater Health Potion',
                'description' => 'A large red potion. Heals 50 HP instantly.',
                'type' => 'consumable',
                'subtype' => 'potion',
                'rarity' => 'rare',
                'stackable' => true,
                'max_stack' => 20,
                'hp_bonus' => 50,
                'base_value' => 200,
            ],
            [
                'name' => 'Energy Elixir',
                'description' => 'A yellow potion that restores 10 energy.',
                'type' => 'consumable',
                'subtype' => 'potion',
                'rarity' => 'rare',
                'stackable' => true,
                'max_stack' => 10,
                'energy_bonus' => 10,
                'base_value' => 500,
            ],

            // Medical supplies
            [
                'name' => 'Bandage',
                'description' => 'Clean linen bandages for treating wounds. Heals 8 HP.',
                'type' => 'consumable',
                'subtype' => 'medical',
                'rarity' => 'common',
                'stackable' => true,
                'max_stack' => 50,
                'hp_bonus' => 8,
                'base_value' => 10,
            ],
            [
                'name' => 'Medicine',
                'description' => 'Herbal medicine that speeds recovery. Heals 20 HP.',
                'type' => 'consumable',
                'subtype' => 'medical',
                'rarity' => 'uncommon',
                'stackable' => true,
                'max_stack' => 20,
                'hp_bonus' => 20,
                'base_value' => 50,
            ],
            [
                'name' => 'Antidote',
                'description' => 'Cures poison and removes toxins from the body.',
                'type' => 'consumable',
                'subtype' => 'medical',
                'rarity' => 'uncommon',
                'stackable' => true,
                'max_stack' => 20,
                'base_value' => 75,
            ],
            [
                'name' => 'Healing Potion',
                'description' => 'A potent healing draught prepared by a physician. Heals 40 HP.',
                'type' => 'consumable',
                'subtype' => 'medical',
                'rarity' => 'rare',
                'stackable' => true,
                'max_stack' => 10,
                'hp_bonus' => 40,
                'base_value' => 150,
            ],

            // Feast items
            [
                'name' => 'Feast Platter',
                'description' => 'A grand platter of assorted meats, cheeses, and delicacies. Heals 50 HP and provides a temporary buff.',
                'type' => 'consumable',
                'subtype' => 'food',
                'rarity' => 'rare',
                'stackable' => true,
                'max_stack' => 5,
                'hp_bonus' => 50,
                'base_value' => 200,
            ],

            // === TOOLS ===
            [
                'name' => 'Bronze Pickaxe',
                'description' => 'A basic pickaxe for mining.',
                'type' => 'tool',
                'subtype' => 'pickaxe',
                'rarity' => 'common',
                'stackable' => false,
                'equipment_slot' => 'weapon',
                'required_skill' => 'mining',
                'required_skill_level' => 1,
                'base_value' => 40,
            ],
            [
                'name' => 'Iron Pickaxe',
                'description' => 'An iron pickaxe for efficient mining.',
                'type' => 'tool',
                'subtype' => 'pickaxe',
                'rarity' => 'common',
                'stackable' => false,
                'equipment_slot' => 'weapon',
                'required_skill' => 'mining',
                'required_skill_level' => 10,
                'base_value' => 150,
            ],
            [
                'name' => 'Steel Pickaxe',
                'description' => 'A high-quality steel pickaxe.',
                'type' => 'tool',
                'subtype' => 'pickaxe',
                'rarity' => 'uncommon',
                'stackable' => false,
                'equipment_slot' => 'weapon',
                'required_skill' => 'mining',
                'required_skill_level' => 30,
                'base_value' => 500,
            ],
            [
                'name' => 'Fishing Rod',
                'description' => 'A basic fishing rod.',
                'type' => 'tool',
                'subtype' => 'fishing',
                'rarity' => 'common',
                'stackable' => false,
                'required_skill' => 'fishing',
                'required_skill_level' => 1,
                'base_value' => 25,
            ],
            [
                'name' => 'Fishing Net',
                'description' => 'A net for catching small fish.',
                'type' => 'tool',
                'subtype' => 'fishing',
                'rarity' => 'common',
                'stackable' => false,
                'required_skill' => 'fishing',
                'required_skill_level' => 5,
                'base_value' => 50,
            ],
            [
                'name' => 'Hammer',
                'description' => 'A smithing hammer for metalwork.',
                'type' => 'tool',
                'subtype' => 'smithing',
                'rarity' => 'common',
                'stackable' => false,
                'required_skill' => 'smithing',
                'required_skill_level' => 1,
                'base_value' => 30,
            ],
            [
                'name' => 'Needle',
                'description' => 'A needle for crafting.',
                'type' => 'tool',
                'subtype' => 'crafting',
                'rarity' => 'common',
                'stackable' => false,
                'required_skill' => 'crafting',
                'required_skill_level' => 1,
                'base_value' => 5,
            ],

            // === MISC ===
            [
                'name' => 'Nails',
                'description' => 'Metal nails for construction and crafting.',
                'type' => 'misc',
                'subtype' => 'material',
                'rarity' => 'common',
                'stackable' => true,
                'max_stack' => 500,
                'base_value' => 1,
            ],
            [
                'name' => 'Bones',
                'description' => 'Bones from a defeated creature.',
                'type' => 'misc',
                'subtype' => 'remains',
                'rarity' => 'common',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 2,
            ],
            [
                'name' => 'Big Bones',
                'description' => 'Large bones from a powerful creature.',
                'type' => 'misc',
                'subtype' => 'remains',
                'rarity' => 'uncommon',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 15,
            ],
            [
                'name' => 'Dragon Bones',
                'description' => 'Rare bones from a slain dragon.',
                'type' => 'misc',
                'subtype' => 'remains',
                'rarity' => 'rare',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 500,
            ],
            [
                'name' => 'Thread',
                'description' => 'A spool of thread for crafting.',
                'type' => 'misc',
                'subtype' => 'material',
                'rarity' => 'common',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 3,
            ],
            [
                'name' => 'Leather',
                'description' => 'Tanned leather for crafting.',
                'type' => 'misc',
                'subtype' => 'material',
                'rarity' => 'common',
                'stackable' => true,
                'max_stack' => 100,
                'base_value' => 10,
            ],

            // Rings and Amulets
            [
                'name' => 'Gold Ring',
                'description' => 'A simple gold ring.',
                'type' => 'armor',
                'subtype' => 'ring',
                'rarity' => 'uncommon',
                'stackable' => false,
                'equipment_slot' => 'ring',
                'base_value' => 200,
            ],
            [
                'name' => 'Ring of Strength',
                'description' => 'A ring imbued with strengthening magic.',
                'type' => 'armor',
                'subtype' => 'ring',
                'rarity' => 'rare',
                'stackable' => false,
                'str_bonus' => 5,
                'equipment_slot' => 'ring',
                'required_level' => 20,
                'base_value' => 1000,
            ],
            [
                'name' => 'Amulet of Defense',
                'description' => 'An amulet that provides protection.',
                'type' => 'armor',
                'subtype' => 'amulet',
                'rarity' => 'rare',
                'stackable' => false,
                'def_bonus' => 5,
                'equipment_slot' => 'amulet',
                'required_level' => 20,
                'base_value' => 1000,
            ],
            [
                'name' => 'Amulet of Power',
                'description' => 'A legendary amulet radiating power.',
                'type' => 'armor',
                'subtype' => 'amulet',
                'rarity' => 'epic',
                'stackable' => false,
                'atk_bonus' => 10,
                'str_bonus' => 10,
                'def_bonus' => 10,
                'equipment_slot' => 'amulet',
                'required_level' => 60,
                'base_value' => 10000,
            ],
        ];

        foreach ($items as $item) {
            Item::updateOrCreate(
                ['name' => $item['name']],
                $item
            );
        }
    }
}
