<?php

namespace Database\Seeders;

use App\Models\Role;
use Illuminate\Database\Seeder;

class RoleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Village Roles
        $villageRoles = [
            [
                'name' => 'Village Elder',
                'slug' => 'elder',
                'icon' => 'crown',
                'description' => 'The elected leader of the village, responsible for governance and village welfare.',
                'location_type' => 'village',
                'permissions' => ['manage_village', 'appoint_roles', 'remove_roles', 'set_taxes', 'moderate_chat'],
                'bonuses' => ['xp_bonus' => 5, 'reputation_bonus' => 10],
                'salary' => 100,
                'tier' => 4,
                'is_elected' => true,
                'max_per_location' => 1,
            ],
            [
                'name' => 'Blacksmith',
                'slug' => 'blacksmith',
                'icon' => 'wrench',
                'description' => 'The village metalworker who maintains equipment and crafts tools.',
                'location_type' => 'village',
                'permissions' => ['access_forge', 'bulk_craft'],
                'bonuses' => ['smithing_xp_bonus' => 10, 'crafting_discount' => 15],
                'salary' => 50,
                'tier' => 2,
                'is_elected' => false,
                'max_per_location' => 1,
            ],
            [
                'name' => 'Merchant',
                'slug' => 'merchant',
                'icon' => 'briefcase',
                'description' => 'The village trader who manages the local market and trade agreements.',
                'location_type' => 'village',
                'permissions' => ['manage_market', 'set_prices', 'trade_bulk'],
                'bonuses' => ['trade_bonus' => 10, 'gold_find_bonus' => 5],
                'salary' => 60,
                'tier' => 2,
                'is_elected' => false,
                'max_per_location' => 1,
            ],
            [
                'name' => 'Guard Captain',
                'slug' => 'guard_captain',
                'icon' => 'shield',
                'description' => 'The head of village defense, responsible for protecting residents.',
                'location_type' => 'village',
                'permissions' => ['manage_guards', 'arrest_criminals', 'patrol'],
                'bonuses' => ['combat_xp_bonus' => 5, 'defense_bonus' => 10],
                'salary' => 75,
                'tier' => 3,
                'is_elected' => false,
                'max_per_location' => 1,
            ],
            [
                'name' => 'Healer',
                'slug' => 'healer',
                'icon' => 'heart',
                'description' => 'The village medic who tends to the sick and wounded.',
                'location_type' => 'village',
                'permissions' => ['free_healing', 'cure_diseases'],
                'bonuses' => ['healing_bonus' => 20, 'hp_regen_bonus' => 5],
                'salary' => 40,
                'tier' => 2,
                'is_elected' => false,
                'max_per_location' => 1,
            ],
            [
                'name' => 'Master Farmer',
                'slug' => 'master_farmer',
                'icon' => 'wheat',
                'description' => 'The village agricultural expert who oversees crops and livestock.',
                'location_type' => 'village',
                'permissions' => ['manage_farms', 'set_harvest_schedule', 'distribute_seeds'],
                'bonuses' => ['farming_xp_bonus' => 15, 'crop_yield_bonus' => 10],
                'salary' => 55,
                'tier' => 2,
                'is_elected' => false,
                'max_per_location' => 1,
            ],
            [
                'name' => 'Innkeeper',
                'slug' => 'innkeeper',
                'icon' => 'beer',
                'description' => 'The keeper of the village tavern where travelers rest and locals gather.',
                'location_type' => 'village',
                'permissions' => ['manage_tavern', 'rent_rooms', 'serve_food'],
                'bonuses' => ['rest_bonus' => 20, 'energy_regen_bonus' => 10],
                'salary' => 45,
                'tier' => 1,
                'is_elected' => false,
                'max_per_location' => 1,
            ],
            [
                'name' => 'Forester',
                'slug' => 'forester',
                'icon' => 'tree-deciduous',
                'description' => 'The village woodsman who manages the forests and timber supply.',
                'location_type' => 'village',
                'permissions' => ['manage_forests', 'sell_to_merchant'],
                'bonuses' => ['woodcutting_xp_bonus' => 15, 'wood_yield_bonus' => 10],
                'salary' => 40,
                'tier' => 1,
                'is_elected' => false,
                'max_per_location' => 1,
            ],
            [
                'name' => 'Fisherman',
                'slug' => 'fisherman',
                'icon' => 'fish',
                'description' => 'The village angler who provides fresh fish to the community.',
                'location_type' => 'village',
                'permissions' => ['manage_fishing', 'sell_to_merchant'],
                'bonuses' => ['fishing_xp_bonus' => 15, 'fish_yield_bonus' => 10],
                'salary' => 35,
                'tier' => 1,
                'is_elected' => false,
                'max_per_location' => 1,
            ],
            [
                'name' => 'Priest',
                'slug' => 'priest',
                'icon' => 'church',
                'description' => 'The spiritual leader who provides blessings, conducts ceremonies, and guides the faithful.',
                'location_type' => 'village',
                'permissions' => ['give_blessings', 'conduct_funerals', 'conduct_marriages'],
                'bonuses' => ['prayer_bonus' => 20, 'morale_bonus' => 10],
                'salary' => 50,
                'tier' => 3,
                'is_elected' => false,
                'max_per_location' => 1,
            ],
            [
                'name' => 'Baker',
                'slug' => 'baker',
                'icon' => 'croissant',
                'description' => 'The village baker who turns grain into bread and pastries.',
                'location_type' => 'village',
                'permissions' => ['bulk_baking', 'sell_to_merchant'],
                'bonuses' => ['cooking_xp_bonus' => 15, 'bread_yield_bonus' => 10],
                'salary' => 35,
                'tier' => 1,
                'is_elected' => false,
                'max_per_location' => 1,
            ],
            [
                'name' => 'Butcher',
                'slug' => 'butcher',
                'icon' => 'beef',
                'description' => 'The village butcher who processes meat and provides cuts to the community.',
                'location_type' => 'village',
                'permissions' => ['process_meat', 'sell_to_merchant'],
                'bonuses' => ['cooking_xp_bonus' => 10, 'meat_yield_bonus' => 15],
                'salary' => 40,
                'tier' => 1,
                'is_elected' => false,
                'max_per_location' => 1,
            ],
            [
                'name' => 'Hunter',
                'slug' => 'hunter',
                'icon' => 'target',
                'description' => 'The village hunter who tracks game and provides meat and hides.',
                'location_type' => 'village',
                'permissions' => ['lead_hunts', 'sell_to_merchant'],
                'bonuses' => ['hunting_xp_bonus' => 15, 'hunt_yield_bonus' => 10],
                'salary' => 45,
                'tier' => 1,
                'is_elected' => false,
                'max_per_location' => 1,
            ],
            [
                'name' => 'Miner',
                'slug' => 'miner',
                'icon' => 'pickaxe',
                'description' => 'The village miner who extracts ore and stone from nearby deposits.',
                'location_type' => 'village',
                'permissions' => ['manage_mines', 'sell_to_merchant'],
                'bonuses' => ['mining_xp_bonus' => 15, 'ore_yield_bonus' => 10],
                'salary' => 45,
                'tier' => 1,
                'is_elected' => false,
                'max_per_location' => 1,
            ],
            [
                'name' => 'Brewer',
                'slug' => 'brewer',
                'icon' => 'hop',
                'description' => 'The village brewer who crafts ales and meads from grain and hops.',
                'location_type' => 'village',
                'permissions' => ['brew_ale', 'sell_to_merchant', 'supply_tavern'],
                'bonuses' => ['brewing_xp_bonus' => 15, 'ale_yield_bonus' => 10],
                'salary' => 40,
                'tier' => 1,
                'is_elected' => false,
                'max_per_location' => 1,
            ],
        ];

        // Barony Roles
        $baronyRoles = [
            [
                'name' => 'Baron',
                'slug' => 'baron',
                'icon' => 'crown',
                'description' => 'The ruler of the barony and surrounding villages, a powerful noble.',
                'location_type' => 'barony',
                'permissions' => ['manage_barony', 'appoint_roles', 'remove_roles', 'set_taxes', 'declare_war', 'moderate_chat'],
                'bonuses' => ['xp_bonus' => 10, 'reputation_bonus' => 20, 'income_bonus' => 15],
                'salary' => 500,
                'tier' => 5,
                'is_elected' => false,
                'max_per_location' => 1,
            ],
            [
                'name' => 'Steward',
                'slug' => 'steward',
                'icon' => 'briefcase',
                'description' => 'The administrator who manages barony affairs and resources.',
                'location_type' => 'barony',
                'permissions' => ['manage_resources', 'manage_staff', 'access_treasury'],
                'bonuses' => ['resource_bonus' => 10, 'efficiency_bonus' => 5],
                'salary' => 200,
                'tier' => 4,
                'is_elected' => false,
                'max_per_location' => 1,
            ],
            [
                'name' => 'Marshal',
                'slug' => 'marshal',
                'icon' => 'swords',
                'description' => 'The military commander of the barony forces.',
                'location_type' => 'barony',
                'permissions' => ['command_troops', 'manage_defenses', 'lead_attacks'],
                'bonuses' => ['combat_xp_bonus' => 15, 'army_bonus' => 10],
                'salary' => 250,
                'tier' => 4,
                'is_elected' => false,
                'max_per_location' => 1,
            ],
            [
                'name' => 'Treasurer',
                'slug' => 'treasurer',
                'icon' => 'wallet',
                'description' => 'The keeper of the barony treasury and financial records.',
                'location_type' => 'barony',
                'permissions' => ['access_treasury', 'manage_finances', 'collect_taxes'],
                'bonuses' => ['gold_bonus' => 10, 'tax_efficiency' => 5],
                'salary' => 175,
                'tier' => 3,
                'is_elected' => false,
                'max_per_location' => 1,
            ],
            [
                'name' => 'Jailsman',
                'slug' => 'jailsman',
                'icon' => 'gavel',
                'description' => 'The warden of the barony dungeon, responsible for prisoners.',
                'location_type' => 'barony',
                'permissions' => ['manage_prison', 'interrogate', 'release_prisoners'],
                'bonuses' => ['intimidation_bonus' => 10],
                'salary' => 100,
                'tier' => 2,
                'is_elected' => false,
                'max_per_location' => 1,
            ],
            [
                'name' => 'Physician',
                'slug' => 'physician',
                'icon' => 'stethoscope',
                'description' => 'The castle doctor who treats wounds, cures diseases, and manages the infirmary.',
                'location_type' => 'barony',
                'permissions' => ['manage_infirmary', 'cure_diseases', 'perform_surgery', 'free_healing'],
                'bonuses' => ['healing_bonus' => 30, 'disease_cure_bonus' => 20],
                'salary' => 150,
                'tier' => 3,
                'is_elected' => false,
                'max_per_location' => 1,
            ],
            [
                'name' => 'Master Cook',
                'slug' => 'master_cook',
                'icon' => 'chef-hat',
                'description' => 'The head of the castle kitchens who prepares feasts and fine cuisine.',
                'location_type' => 'barony',
                'permissions' => ['manage_kitchen', 'prepare_feasts', 'sell_to_merchant'],
                'bonuses' => ['cooking_xp_bonus' => 20, 'food_quality_bonus' => 15],
                'salary' => 100,
                'tier' => 2,
                'is_elected' => false,
                'max_per_location' => 1,
            ],
            [
                'name' => 'Castellan',
                'slug' => 'castellan',
                'icon' => 'castle',
                'description' => 'The keeper of the castle who manages daily operations and acts in the Baron\'s absence.',
                'location_type' => 'barony',
                'permissions' => ['manage_castle', 'manage_staff', 'minor_appointments', 'access_treasury'],
                'bonuses' => ['efficiency_bonus' => 10, 'reputation_bonus' => 5],
                'salary' => 175,
                'tier' => 4,
                'is_elected' => false,
                'max_per_location' => 1,
            ],
            [
                'name' => 'Court Chaplain',
                'slug' => 'court_chaplain',
                'icon' => 'church',
                'description' => 'The spiritual advisor to the Baron, conducting ceremonies and providing blessings.',
                'location_type' => 'barony',
                'permissions' => ['give_blessings', 'conduct_ceremonies', 'advise_baron', 'conduct_marriages'],
                'bonuses' => ['prayer_bonus' => 25, 'morale_bonus' => 15],
                'salary' => 125,
                'tier' => 3,
                'is_elected' => false,
                'max_per_location' => 1,
            ],
            [
                'name' => 'Castle Stablemaster',
                'slug' => 'castle_stablemaster',
                'icon' => 'horse',
                'description' => 'The master of the castle stables, overseeing warhorses and stable hands.',
                'location_type' => 'barony',
                'permissions' => ['manage_stables', 'buy_horses', 'sell_horses', 'train_warhorses'],
                'bonuses' => ['horse_care_bonus' => 20, 'warhorse_training_bonus' => 10],
                'salary' => 140,
                'tier' => 3,
                'is_elected' => false,
                'max_per_location' => 1,
            ],
        ];

        // Town Roles
        $townRoles = [
            [
                'name' => 'Mayor',
                'slug' => 'mayor',
                'icon' => 'crown',
                'description' => 'The elected leader of the town, responsible for governance and civic affairs.',
                'location_type' => 'town',
                'permissions' => ['manage_town', 'appoint_roles', 'remove_roles', 'set_taxes', 'moderate_chat'],
                'bonuses' => ['xp_bonus' => 10, 'reputation_bonus' => 15, 'income_bonus' => 10],
                'salary' => 300,
                'tier' => 4,
                'is_elected' => true,
                'max_per_location' => 1,
            ],
            [
                'name' => 'Town Guard Captain',
                'slug' => 'town_guard_captain',
                'icon' => 'shield',
                'description' => 'The head of the town watch, maintaining law and order.',
                'location_type' => 'town',
                'permissions' => ['manage_guards', 'arrest_criminals', 'patrol', 'enforce_curfew'],
                'bonuses' => ['combat_xp_bonus' => 10, 'defense_bonus' => 15],
                'salary' => 200,
                'tier' => 3,
                'is_elected' => false,
                'max_per_location' => 1,
            ],
            [
                'name' => 'Guildmaster',
                'slug' => 'guildmaster',
                'icon' => 'users',
                'description' => 'The overseer of guild affairs in the town, mediating between craftsmen.',
                'location_type' => 'town',
                'permissions' => ['manage_guilds', 'approve_guild_charters', 'settle_guild_disputes', 'set_guild_fees'],
                'bonuses' => ['crafting_xp_bonus' => 15, 'reputation_bonus' => 10],
                'salary' => 175,
                'tier' => 3,
                'is_elected' => false,
                'max_per_location' => 1,
            ],
            [
                'name' => 'Magistrate',
                'slug' => 'magistrate',
                'icon' => 'gavel',
                'description' => 'The town judge who presides over local courts, settles civil disputes, issues fines, and sentences criminals. A respected arbiter of justice.',
                'location_type' => 'town',
                'permissions' => ['preside_trials', 'issue_fines', 'sentence_criminals', 'settle_disputes'],
                'bonuses' => ['reputation_bonus' => 10, 'legitimacy_bonus' => 5],
                'salary' => 150,
                'tier' => 3,
                'is_elected' => false,
                'max_per_location' => 1,
            ],
            [
                'name' => 'Harbormaster',
                'slug' => 'harbormaster',
                'icon' => 'anchor',
                'description' => 'The manager of the town port, overseeing ships and maritime trade.',
                'location_type' => 'town',
                'permissions' => ['manage_port', 'collect_docking_fees', 'inspect_cargo', 'grant_berths'],
                'bonuses' => ['trade_bonus' => 15, 'gold_find_bonus' => 10],
                'salary' => 125,
                'tier' => 2,
                'is_elected' => false,
                'max_per_location' => 1,
            ],
            [
                'name' => 'Town Clerk',
                'slug' => 'town_clerk',
                'icon' => 'scroll',
                'description' => 'The keeper of town records, handling administration and documentation.',
                'location_type' => 'town',
                'permissions' => ['manage_records', 'issue_permits', 'register_businesses', 'certify_documents'],
                'bonuses' => ['efficiency_bonus' => 10],
                'salary' => 100,
                'tier' => 2,
                'is_elected' => false,
                'max_per_location' => 1,
            ],
            [
                'name' => 'Market Warden',
                'slug' => 'market_warden',
                'icon' => 'store',
                'description' => 'The regulator of trade, ensuring fair weights, measures, and prices.',
                'location_type' => 'town',
                'permissions' => ['manage_market', 'inspect_goods', 'set_price_controls', 'license_merchants'],
                'bonuses' => ['trade_bonus' => 10, 'gold_bonus' => 5],
                'salary' => 110,
                'tier' => 2,
                'is_elected' => false,
                'max_per_location' => 1,
            ],
            [
                'name' => 'Town Physician',
                'slug' => 'town_physician',
                'icon' => 'stethoscope',
                'description' => 'The town doctor who treats the sick and manages public health.',
                'location_type' => 'town',
                'permissions' => ['manage_infirmary', 'cure_diseases', 'quarantine', 'free_healing'],
                'bonuses' => ['healing_bonus' => 25, 'disease_cure_bonus' => 15],
                'salary' => 140,
                'tier' => 3,
                'is_elected' => false,
                'max_per_location' => 1,
            ],
            [
                'name' => 'Head Chef',
                'slug' => 'head_chef',
                'icon' => 'chef-hat',
                'description' => 'The master of the town\'s main kitchen, supplying inns and hosting feasts.',
                'location_type' => 'town',
                'permissions' => ['manage_kitchen', 'prepare_feasts', 'sell_to_merchant', 'supply_inns'],
                'bonuses' => ['cooking_xp_bonus' => 15, 'food_quality_bonus' => 10],
                'salary' => 90,
                'tier' => 2,
                'is_elected' => false,
                'max_per_location' => 1,
            ],
            [
                'name' => 'Town Crier',
                'slug' => 'town_crier',
                'icon' => 'megaphone',
                'description' => 'The voice of the town, announcing news, events, and proclamations.',
                'location_type' => 'town',
                'permissions' => ['make_announcements', 'spread_news', 'announce_events'],
                'bonuses' => ['reputation_bonus' => 5],
                'salary' => 50,
                'tier' => 1,
                'is_elected' => false,
                'max_per_location' => 1,
            ],

            // Skilled Trade Roles
            [
                'name' => 'Master Blacksmith',
                'slug' => 'master_blacksmith',
                'icon' => 'anvil',
                'description' => 'The finest metalworker in town, capable of crafting superior weapons and tools.',
                'location_type' => 'town',
                'permissions' => ['access_forge', 'bulk_craft', 'craft_masterwork', 'train_apprentices'],
                'bonuses' => ['smithing_xp_bonus' => 20, 'crafting_discount' => 20],
                'salary' => 120,
                'tier' => 3,
                'is_elected' => false,
                'max_per_location' => 1,
            ],
            [
                'name' => 'Weaponsmith',
                'slug' => 'weaponsmith',
                'icon' => 'swords',
                'description' => 'A specialist in forging weapons of war, from daggers to greatswords.',
                'location_type' => 'town',
                'permissions' => ['forge_weapons', 'bulk_craft', 'sell_to_merchant'],
                'bonuses' => ['smithing_xp_bonus' => 15, 'weapon_quality_bonus' => 15],
                'salary' => 100,
                'tier' => 2,
                'is_elected' => false,
                'max_per_location' => 1,
            ],
            [
                'name' => 'Armorsmith',
                'slug' => 'armorsmith',
                'icon' => 'shield',
                'description' => 'A specialist in forging armor and protective gear.',
                'location_type' => 'town',
                'permissions' => ['forge_armor', 'bulk_craft', 'sell_to_merchant'],
                'bonuses' => ['smithing_xp_bonus' => 15, 'armor_quality_bonus' => 15],
                'salary' => 100,
                'tier' => 2,
                'is_elected' => false,
                'max_per_location' => 1,
            ],
            [
                'name' => 'Master Jeweler',
                'slug' => 'master_jeweler',
                'icon' => 'gem',
                'description' => 'A craftsman of fine jewelry and gem-cutting.',
                'location_type' => 'town',
                'permissions' => ['craft_jewelry', 'cut_gems', 'appraise_gems', 'sell_to_merchant'],
                'bonuses' => ['crafting_xp_bonus' => 15, 'gem_quality_bonus' => 20],
                'salary' => 130,
                'tier' => 3,
                'is_elected' => false,
                'max_per_location' => 1,
            ],
            [
                'name' => 'Master Tailor',
                'slug' => 'master_tailor',
                'icon' => 'scissors',
                'description' => 'A skilled craftsman of fine clothing and fabric goods.',
                'location_type' => 'town',
                'permissions' => ['craft_clothing', 'bulk_craft', 'sell_to_merchant'],
                'bonuses' => ['crafting_xp_bonus' => 15, 'clothing_quality_bonus' => 15],
                'salary' => 85,
                'tier' => 2,
                'is_elected' => false,
                'max_per_location' => 1,
            ],
            [
                'name' => 'Master Carpenter',
                'slug' => 'master_carpenter',
                'icon' => 'hammer',
                'description' => 'An expert woodworker who crafts furniture, buildings, and fine wood items.',
                'location_type' => 'town',
                'permissions' => ['craft_wood_items', 'build_structures', 'bulk_craft', 'sell_to_merchant'],
                'bonuses' => ['woodcutting_xp_bonus' => 10, 'crafting_xp_bonus' => 15],
                'salary' => 95,
                'tier' => 2,
                'is_elected' => false,
                'max_per_location' => 1,
            ],
            [
                'name' => 'Alchemist',
                'slug' => 'alchemist',
                'icon' => 'flask-conical',
                'description' => 'A master of potions, elixirs, and mysterious concoctions.',
                'location_type' => 'town',
                'permissions' => ['brew_potions', 'identify_potions', 'sell_to_merchant'],
                'bonuses' => ['alchemy_xp_bonus' => 20, 'potion_quality_bonus' => 15],
                'salary' => 140,
                'tier' => 3,
                'is_elected' => false,
                'max_per_location' => 1,
            ],
            [
                'name' => 'Tanner',
                'slug' => 'tanner',
                'icon' => 'scroll',
                'description' => 'A craftsman who processes hides into leather for armor and goods.',
                'location_type' => 'town',
                'permissions' => ['process_leather', 'craft_leather_goods', 'sell_to_merchant'],
                'bonuses' => ['crafting_xp_bonus' => 15, 'leather_quality_bonus' => 15],
                'salary' => 75,
                'tier' => 2,
                'is_elected' => false,
                'max_per_location' => 1,
            ],
            [
                'name' => 'Scribe',
                'slug' => 'scribe',
                'icon' => 'pen-tool',
                'description' => 'A learned person who copies documents, writes contracts, and creates scrolls.',
                'location_type' => 'town',
                'permissions' => ['copy_documents', 'create_scrolls', 'notarize', 'sell_to_merchant'],
                'bonuses' => ['magic_xp_bonus' => 10, 'reputation_bonus' => 5],
                'salary' => 80,
                'tier' => 2,
                'is_elected' => false,
                'max_per_location' => 1,
            ],
            [
                'name' => 'Master Miner',
                'slug' => 'master_miner',
                'icon' => 'pickaxe',
                'description' => 'An expert miner who extracts the finest ores and precious gems.',
                'location_type' => 'town',
                'permissions' => ['manage_mines', 'extract_rare_ore', 'train_apprentices', 'sell_to_merchant'],
                'bonuses' => ['mining_xp_bonus' => 25, 'ore_yield_bonus' => 20],
                'salary' => 110,
                'tier' => 3,
                'is_elected' => false,
                'max_per_location' => 1,
            ],
            [
                'name' => 'Master Fisher',
                'slug' => 'master_fisher',
                'icon' => 'fish',
                'description' => 'The most skilled angler in town, catching the rarest fish.',
                'location_type' => 'town',
                'permissions' => ['manage_fishing', 'catch_rare_fish', 'train_apprentices', 'sell_to_merchant'],
                'bonuses' => ['fishing_xp_bonus' => 25, 'fish_yield_bonus' => 20],
                'salary' => 90,
                'tier' => 3,
                'is_elected' => false,
                'max_per_location' => 1,
            ],
            [
                'name' => 'Brewmaster',
                'slug' => 'brewmaster',
                'icon' => 'beer',
                'description' => 'A master brewer who crafts the finest ales, wines, and spirits.',
                'location_type' => 'town',
                'permissions' => ['brew_ale', 'brew_wine', 'brew_spirits', 'supply_taverns', 'sell_to_merchant'],
                'bonuses' => ['brewing_xp_bonus' => 25, 'ale_quality_bonus' => 20],
                'salary' => 95,
                'tier' => 3,
                'is_elected' => false,
                'max_per_location' => 1,
            ],
            [
                'name' => 'Stablemaster',
                'slug' => 'stablemaster',
                'icon' => 'horse',
                'description' => 'The keeper of the town stables, responsible for horses and stable hands.',
                'location_type' => 'town',
                'permissions' => ['manage_stables', 'buy_horses', 'sell_horses', 'train_horses'],
                'bonuses' => ['horse_care_bonus' => 15],
                'salary' => 90,
                'tier' => 2,
                'is_elected' => false,
                'max_per_location' => 1,
            ],
        ];

        // Duchy Roles
        $duchyRoles = [
            [
                'name' => 'Duke',
                'slug' => 'duke',
                'icon' => 'crown',
                'description' => 'The ruler of the duchy, overseeing multiple baronies and answering only to the King.',
                'location_type' => 'duchy',
                'permissions' => ['rule_duchy', 'appoint_roles', 'remove_roles', 'set_duchy_taxes', 'command_duchy_forces', 'moderate_chat'],
                'bonuses' => ['xp_bonus' => 15, 'reputation_bonus' => 30, 'income_bonus' => 20],
                'salary' => 1200,
                'tier' => 5,
                'is_elected' => false,
                'max_per_location' => 1,
            ],
            [
                'name' => 'Duchy Chancellor',
                'slug' => 'duchy_chancellor',
                'icon' => 'scale',
                'description' => 'The chief advisor to the Duke, managing diplomacy and legal matters.',
                'location_type' => 'duchy',
                'permissions' => ['manage_diplomacy', 'draft_laws', 'advise_duke', 'negotiate_treaties'],
                'bonuses' => ['reputation_bonus' => 12, 'diplomacy_bonus' => 15],
                'salary' => 450,
                'tier' => 4,
                'is_elected' => false,
                'max_per_location' => 1,
            ],
            [
                'name' => 'Duchy Marshal',
                'slug' => 'duchy_marshal',
                'icon' => 'swords',
                'description' => 'The commander of the duchy\'s military forces.',
                'location_type' => 'duchy',
                'permissions' => ['command_troops', 'manage_defenses', 'lead_attacks', 'train_soldiers'],
                'bonuses' => ['combat_xp_bonus' => 15, 'army_bonus' => 15],
                'salary' => 550,
                'tier' => 4,
                'is_elected' => false,
                'max_per_location' => 1,
            ],
            [
                'name' => 'Duchy Treasurer',
                'slug' => 'duchy_treasurer',
                'icon' => 'wallet',
                'description' => 'The keeper of the duchy treasury and financial records.',
                'location_type' => 'duchy',
                'permissions' => ['access_treasury', 'manage_finances', 'collect_taxes', 'audit_baronies'],
                'bonuses' => ['gold_bonus' => 15, 'tax_efficiency' => 10],
                'salary' => 400,
                'tier' => 4,
                'is_elected' => false,
                'max_per_location' => 1,
            ],
            [
                'name' => 'Duchy Physician',
                'slug' => 'duchy_physician',
                'icon' => 'stethoscope',
                'description' => 'The chief medical officer of the duchy, overseeing health across the realm.',
                'location_type' => 'duchy',
                'permissions' => ['manage_health', 'cure_diseases', 'perform_surgery', 'quarantine_areas'],
                'bonuses' => ['healing_bonus' => 35, 'disease_cure_bonus' => 25],
                'salary' => 350,
                'tier' => 3,
                'is_elected' => false,
                'max_per_location' => 1,
            ],
            [
                'name' => 'Duchy Chef',
                'slug' => 'duchy_chef',
                'icon' => 'chef-hat',
                'description' => 'The head chef of the ducal court, preparing grand feasts.',
                'location_type' => 'duchy',
                'permissions' => ['manage_kitchen', 'prepare_feasts', 'organize_banquets'],
                'bonuses' => ['cooking_xp_bonus' => 20, 'food_quality_bonus' => 15],
                'salary' => 250,
                'tier' => 3,
                'is_elected' => false,
                'max_per_location' => 1,
            ],
            [
                'name' => 'High Priest',
                'slug' => 'high_priest',
                'icon' => 'church',
                'description' => 'The spiritual leader of the duchy, overseeing religious affairs.',
                'location_type' => 'duchy',
                'permissions' => ['lead_religion', 'give_blessings', 'conduct_ceremonies', 'advise_duke'],
                'bonuses' => ['prayer_bonus' => 30, 'morale_bonus' => 20],
                'salary' => 300,
                'tier' => 4,
                'is_elected' => false,
                'max_per_location' => 1,
            ],
            [
                'name' => 'Master of Hunts',
                'slug' => 'master_of_hunts',
                'icon' => 'target',
                'description' => 'The organizer of ducal hunts and manager of game preserves.',
                'location_type' => 'duchy',
                'permissions' => ['organize_hunts', 'manage_preserves', 'enforce_hunting_laws'],
                'bonuses' => ['hunting_xp_bonus' => 20, 'hunt_yield_bonus' => 15],
                'salary' => 200,
                'tier' => 3,
                'is_elected' => false,
                'max_per_location' => 1,
            ],
            [
                'name' => 'Ducal Stablemaster',
                'slug' => 'ducal_stablemaster',
                'icon' => 'horse',
                'description' => 'The master of the ducal stables, overseeing the Duke\'s prized horses.',
                'location_type' => 'duchy',
                'permissions' => ['manage_stables', 'buy_horses', 'sell_horses', 'train_warhorses', 'breed_horses'],
                'bonuses' => ['horse_care_bonus' => 25, 'warhorse_training_bonus' => 15],
                'salary' => 220,
                'tier' => 3,
                'is_elected' => false,
                'max_per_location' => 1,
            ],
        ];

        // Kingdom Roles
        $kingdomRoles = [
            [
                'name' => 'King',
                'slug' => 'king',
                'icon' => 'crown',
                'description' => 'The supreme ruler of the kingdom, elected by the lords.',
                'location_type' => 'kingdom',
                'permissions' => ['rule_kingdom', 'appoint_roles', 'remove_roles', 'set_kingdom_taxes', 'declare_war', 'make_laws', 'moderate_chat'],
                'bonuses' => ['xp_bonus' => 20, 'reputation_bonus' => 50, 'income_bonus' => 25],
                'salary' => 2000,
                'tier' => 5,
                'is_elected' => true,
                'max_per_location' => 1,
            ],
            [
                'name' => 'Chancellor',
                'slug' => 'chancellor',
                'icon' => 'scale',
                'description' => 'The chief advisor to the King, managing diplomacy and laws.',
                'location_type' => 'kingdom',
                'permissions' => ['manage_diplomacy', 'draft_laws', 'advise_king'],
                'bonuses' => ['reputation_bonus' => 15, 'diplomacy_bonus' => 20],
                'salary' => 800,
                'tier' => 4,
                'is_elected' => false,
                'max_per_location' => 1,
            ],
            [
                'name' => 'General',
                'slug' => 'general',
                'icon' => 'swords',
                'description' => 'The supreme commander of the kingdom\'s military forces.',
                'location_type' => 'kingdom',
                'permissions' => ['command_armies', 'manage_military', 'lead_campaigns'],
                'bonuses' => ['combat_xp_bonus' => 20, 'army_bonus' => 20],
                'salary' => 1500,
                'tier' => 4,
                'is_elected' => false,
                'max_per_location' => 1,
            ],
            [
                'name' => 'Royal Treasurer',
                'slug' => 'royal_treasurer',
                'icon' => 'wallet',
                'description' => 'The keeper of the royal treasury and kingdom finances.',
                'location_type' => 'kingdom',
                'permissions' => ['access_royal_treasury', 'manage_kingdom_finances', 'collect_kingdom_taxes'],
                'bonuses' => ['gold_bonus' => 20, 'tax_efficiency' => 15],
                'salary' => 1250,
                'tier' => 4,
                'is_elected' => false,
                'max_per_location' => 1,
            ],
            [
                'name' => 'Archbishop',
                'slug' => 'archbishop',
                'icon' => 'church',
                'description' => 'The highest religious authority in the kingdom, spiritual advisor to the crown and head of the faith.',
                'location_type' => 'kingdom',
                'permissions' => ['lead_religion', 'crown_monarch', 'excommunicate', 'give_blessings', 'conduct_royal_ceremonies', 'advise_king'],
                'bonuses' => ['prayer_bonus' => 40, 'morale_bonus' => 25, 'reputation_bonus' => 20],
                'salary' => 700,
                'tier' => 4,
                'is_elected' => false,
                'max_per_location' => 1,
            ],
            [
                'name' => 'Royal Steward',
                'slug' => 'royal_steward',
                'icon' => 'home',
                'description' => 'The manager of the royal household, overseeing the court and palace affairs.',
                'location_type' => 'kingdom',
                'permissions' => ['manage_royal_household', 'organize_feasts', 'manage_court_staff', 'access_royal_treasury'],
                'bonuses' => ['efficiency_bonus' => 15, 'reputation_bonus' => 10],
                'salary' => 500,
                'tier' => 4,
                'is_elected' => false,
                'max_per_location' => 1,
            ],
            [
                'name' => 'Lord Marshal',
                'slug' => 'lord_marshal',
                'icon' => 'shield',
                'description' => 'The chief law enforcement officer of the kingdom, responsible for keeping the peace.',
                'location_type' => 'kingdom',
                'permissions' => ['enforce_laws', 'arrest_criminals', 'command_guards', 'manage_bounties', 'investigate_crimes'],
                'bonuses' => ['combat_xp_bonus' => 10, 'intimidation_bonus' => 20],
                'salary' => 650,
                'tier' => 4,
                'is_elected' => false,
                'max_per_location' => 1,
            ],
            [
                'name' => 'Master of Laws',
                'slug' => 'master_of_laws',
                'icon' => 'gavel',
                'description' => 'The Chief Justice of the kingdom, presiding over royal courts and interpreting the law.',
                'location_type' => 'kingdom',
                'permissions' => ['preside_trials', 'interpret_laws', 'issue_pardons', 'advise_king', 'appoint_judges'],
                'bonuses' => ['reputation_bonus' => 15, 'legitimacy_bonus' => 10],
                'salary' => 550,
                'tier' => 4,
                'is_elected' => false,
                'max_per_location' => 1,
            ],
            [
                'name' => 'Spymaster',
                'slug' => 'spymaster',
                'icon' => 'eye',
                'description' => 'The master of whispers, running the kingdom\'s intelligence network and uncovering secrets.',
                'location_type' => 'kingdom',
                'permissions' => ['manage_spies', 'gather_intelligence', 'counter_espionage', 'advise_king', 'uncover_plots'],
                'bonuses' => ['stealth_bonus' => 25, 'intrigue_bonus' => 30],
                'salary' => 750,
                'tier' => 4,
                'is_elected' => false,
                'max_per_location' => 1,
            ],
            [
                'name' => 'Royal Herald',
                'slug' => 'royal_herald',
                'icon' => 'megaphone',
                'description' => 'The voice of the crown, announcing proclamations, organizing tournaments, and managing heraldry.',
                'location_type' => 'kingdom',
                'permissions' => ['make_proclamations', 'organize_tournaments', 'manage_heraldry', 'conduct_ceremonies', 'announce_events'],
                'bonuses' => ['reputation_bonus' => 10, 'event_bonus' => 20],
                'salary' => 400,
                'tier' => 3,
                'is_elected' => false,
                'max_per_location' => 1,
            ],
            [
                'name' => 'Royal Physician',
                'slug' => 'royal_physician',
                'icon' => 'stethoscope',
                'description' => 'The personal doctor to the royal family, the finest medical mind in the kingdom.',
                'location_type' => 'kingdom',
                'permissions' => ['treat_royalty', 'manage_royal_health', 'cure_diseases', 'perform_surgery', 'advise_king'],
                'bonuses' => ['healing_bonus' => 50, 'disease_cure_bonus' => 40],
                'salary' => 1750,
                'tier' => 4,
                'is_elected' => false,
                'max_per_location' => 1,
            ],
            [
                'name' => 'Royal Chef',
                'slug' => 'royal_chef',
                'icon' => 'chef-hat',
                'description' => 'The master of the royal kitchens, preparing feasts for the court and tasting for poison.',
                'location_type' => 'kingdom',
                'permissions' => ['manage_royal_kitchen', 'prepare_royal_feasts', 'taste_for_poison', 'organize_banquets'],
                'bonuses' => ['cooking_xp_bonus' => 30, 'food_quality_bonus' => 25],
                'salary' => 950,
                'tier' => 3,
                'is_elected' => false,
                'max_per_location' => 1,
            ],
            [
                'name' => 'Royal Stablemaster',
                'slug' => 'royal_stablemaster',
                'icon' => 'horse',
                'description' => 'The master of the royal stables, overseeing the King\'s legendary warhorses.',
                'location_type' => 'kingdom',
                'permissions' => ['manage_royal_stables', 'buy_horses', 'sell_horses', 'train_warhorses', 'breed_royal_horses'],
                'bonuses' => ['horse_care_bonus' => 35, 'warhorse_training_bonus' => 25],
                'salary' => 400,
                'tier' => 4,
                'is_elected' => false,
                'max_per_location' => 1,
            ],
        ];

        $allRoles = array_merge($villageRoles, $baronyRoles, $townRoles, $duchyRoles, $kingdomRoles);

        foreach ($allRoles as $roleData) {
            Role::updateOrCreate(
                ['slug' => $roleData['slug']],
                $roleData
            );
        }
    }
}
